[REV]
ID=1.0.0
APP=IC-PCR1000  Revision 2.2
SOURCE=/home/mainmeister/Projects/RadioReference2PCR1000/metro_22.csv

[BANK00]
BANKNAME=Clarington
00=Darlington Provincial Park Interpark
01=Darlington Provincial Park Operations
02=Darlington Provincial Park
03=Clarington Fire Services  Paging

[BANK01]
BANKNAME=Georgina Township
00=Sibbald Point Provincial Park  OMNR CH09

[BANK02]
BANKNAME=Hydro One
00=Hydro One
01=Hydro One

[BANK03]
BANKNAME=Dundas
00=Spare Work Channel
01=Dispatch

[BANK04]
BANKNAME=6 M Band
00=VE3SIX  Uxbridge
01=VA3PTX  Pefferlaw
02=VE3WIK  Carlisle
03=VA3PWR  Ballantrae
04=VE3PRC  Brampton
05=VE3MIS  Mississauga
06=VA3GTU  Toronto
07=VA3ECT  Toronto
08=VE3BUO  Burlington 

[BANK05]
BANKNAME=Attractions Canadian Tire Motorsport Park
00=CTMP FM Broadcast
01=CTMP Ch 1 TowerKarting Track Operations
02=Bobs Towing wCTMP
03=Speed TV crews
04=Speed TV crews
05=Pratt  Miller Engineering and Fabrication
06=CTMP Control
07=NASCAR Ch 1 Safety
08=Bridgestone Racing Academy
09=CTMP Driver Development Track
10=CTMP Ch 5
11=CTMP MedicalSecurity
12=CTMP OperationsSafety
13=CTMP OpsSafety OldBackup
14=CTMP MedicalSecurity OldBackup
15=Flying Lizard Motorsport
16=Star Mazda Series Racing Ch 2
17=Star Mazda Series Racing Ch 1
18=Flying Lizard Motorsport
19=CBS Sports Feed

[BANK06]
BANKNAME=Billy Bishop Toronto City Airport YTZ Air Traffic Control
00=Toronto Island Localizer Runways 08  26
01=Tower
02=Tower alternate
03=Ground
04=ATIS

[BANK07]
BANKNAME=Buttonville Airport YKZ Air Traffic Control
00=ILS  Distance MeasuringLocalizer
01=Tower alternate
02=Ground
03=Toronto Radio
04=Tower
05=Toronto Radio Enroute
06=Buttonville ATIS

[BANK08]
BANKNAME=Oshawa Airport YOO CYOO Oshawa Airport
00=Oshawa DMELOC Decommissioned June 2015
01=Oshawa Ground
02=Oshawa Tower
03=Oshawa ATIS

[BANK09]
BANKNAME=Canadian International Air Show CNE Waterfront
00=Snowbirds
01=Show Radar
02=Boss Control
03=Snowbirds
04=Tiger Ops
05=Snowbirds
06=Hornets

[BANK10]
BANKNAME=Toronto Pearson International Airport YYZ Air Traffic Control
00=Tower Backup
01=Tower South
02=Tower North
03=Ground Center
04=ATIS Primary
05=Clearance Delivery
06=Ground North
07=Ground South
08=ATIS Secondary

[BANK11]
BANKNAME=John C Munro International Airport YHM Air Traffic Control
00=Ground
01=Tower  Primary
02=ATIS

[BANK12]
BANKNAME=Toronto Pearson International Airport YYZ Apron Control
00=South Apron  Terminal 1  East Satellite Ramp  GTAA Hangar  Avitat Ramps
01=North Apron  Terminal 3  T3 Satellite   Cargo West  Fedex
02=Backup
03=Apron CoOrdinator

[BANK13]
BANKNAME=Buttonville Airport YKZ Aviation Business Frequencies
00=Seneca College Flight School Hangars 678
01=National Helicopters   Hangar 11A

[BANK14]
BANKNAME=John C Munro International Airport YHM Airport Services
00=Hamilton Jetport Ltd
01=Shell  Glanford Aviation Services
02=Esso  Hanger 3

[BANK15]
BANKNAME=Greenbank Airfield CNP8  Air Traffic Control 
00=ATFUNICOM 5NM4000ASL

[BANK16]
BANKNAME=Baldwin Airport CBP9 Air Traffic Control
00=Unicom

[BANK17]
BANKNAME=Toronto Pearson International Airport YYZ Private Aviation  Business
00=Landmark Aviation
01=Private Jet Charter Service

[BANK18]
BANKNAME=John C Munro International Airport YHM General Aviation
00=Peninsulair Flight School
01=Hamilton Flying Club

[BANK19]
BANKNAME=Downsview Airport YZD Air Traffic Control 
00=Automated Weather
01=Unicom  Tower

[BANK20]
BANKNAME=Billy Bishop Toronto City Airport YTZ Operations
00=ESSO Aviation
01=Porter  Fixed Base Operations 
02=Toronto Port Authority  City Airport  Runway Snow Clearing 
03=Toronto Port Authority  City Airport  Maintenance

[BANK21]
BANKNAME=Toronto Pearson International Airport YYZ Airport Services
00=FSS  London Flight Information Centre RCO
01=Field Aviation East
02=SkyserviceEsso Avitat
03=Central DeIcing Facility  Pads 4 5 6
04=Central DeIcing Facility
05=Central DeIcing Facility  Pads 1 2 3
06=Central DeIcing Facility Back up

[BANK22]
BANKNAME=BramptonCaledon Airport CNC3 Caledon
00=Brampton Flying Club

[BANK23]
BANKNAME=Buttonville Airport YKZ Support Services
00=Toronto Airways

[BANK24]
BANKNAME=Burlington Airpark  ZBA Air Traffic Control
00=Spectrum Airways

[BANK25]
BANKNAME=Toronto Pearson International Airport YYZ Airlines
00=WestJet
01=Air Canada Jazz
02=American Airlines
03=Air Georgian
04=ARINC
05=Air Canada Jazz Maintenance
06=Air Canada Flight Dispatch
07=Air Canada International Flights
08=Air Canada Jazz Maintenance
09=Air Canada Domestic Flights
10=Delta Airlines
11=Swissport
12=Air Canada Station Operations Centre
13=US Airways
14=Air Transat
15=Airport Terminal Services

[BANK26]
BANKNAME=Toronto Pearson International Airport YYZ Toronto Centre  Terminal Control Unit
00=Arrivals 2
01=Arrivals 3
02=North Departure
03=South Departure
04=Arrivals 1
05=ILS Monitor 

[BANK27]
BANKNAME=Billy Bishop Toronto City Airport YTZ CYTZ
00=Air Canada Rapidair
01=Porter Airlines
02=Porter Airlines
03=Porter Airlines

[BANK28]
BANKNAME=John C Munro International Airport YHM Cargo Carriers
00=Purolator Courier Ltd
01=United Parcel Service Canada
02=Cargo Jet Canada Ltd
03=Federal Express Canada

[BANK29]
BANKNAME=Oshawa Airport YOO Flight School
00=Canadian Flight Academy

[BANK30]
BANKNAME=Toronto Pearson International Airport YYZ ACARS
00=ARINC Toronto
01=ARINC Toronto
02=ARINC Toronto
03=ARINC Toronto
04=SITACOM Canada
05=ARINC Toronto  VDL Mode 2

[BANK31]
BANKNAME=Downsview Airport YZD Bombardier Aerospace
00=Tower
01=Plant Operations

[BANK32]
BANKNAME=Oshawa Airport YOO Fuel Operations
00=Enterprise Air

[BANK33]
BANKNAME=John C Munro International Airport YHM Airlines
00=CanJet
01=WestJet
02=Westjet  Ops
03=Air Transat Operations

[BANK34]
BANKNAME=Toronto Pearson International Airport YYZ Cargo Carriers
00=Federal Express

[BANK35]
BANKNAME=Business Georgetown
00=First Student Canada

[BANK36]
BANKNAME=Business Burlington
00=First Student Canada
01=Dufferin Concrete  
02=Canadian Building Materials 
03=Burlington Taxi
04=Contro Valve
05=Burlington Mall  Security
06=Attridge Transportation 
07=Mapleview Centre  Security
08=Attridge Transportation 
09=Homestead LandHoldings  Maintenance

[BANK37]
BANKNAME=Business Markham
00=First Canada ULC
01=Markham Taxi
02=Markville Shopping Centre  Security 
03=Markville Shopping Centre  Property Management

[BANK38]
BANKNAME=Business King City
00=Sharp Bus Lines Ch 1
01=Sharp Bus Lines Ch 2
02=A Cab Taxi Services
03=First Student Canada
04=Stock Transportation

[BANK39]
BANKNAME=Transportation Caledon East
00=First Student Canada
01=First Student Canada

[BANK40]
BANKNAME=Business Oakville
00=First Student Canada
01=Halton Taxi
02=Stock Transportation
03=BOT Construction 
04=BOT Construction 
05=Oakville Place  Security  
06=Hopedale Mall  Security 
07=Trafalgar Heights  Property Management
08=United Taxi
09=Holiday Inn Select 
10=5 Drive In Theatre
11=Home Depot  2555 Bristol Circle

[BANK41]
BANKNAME=Transportation Brampton
00=Stock Transportation
01=Switzer Carty
02=Parkinson Coach Lines 
03=Stock Transportation
04=Kwik Cab 
05=Bram City Taxi
06=Attridge Transportation
07=A Seven Eleven Taxi 
08=Airline Limo

[BANK42]
BANKNAME=  Bell FleetNet  Ontario Provincial Government Zone 1
00=Site 039 King City 39KING
01=Site 040 Mowat 40MOWT Toronto
02=Site 005 Ballinafad 05BALL
03=Site 037 Whitby 37WHIT
04=Site 007 Charlton 07CHAR Hamilton
05=Site 009 Britannia 09BRIT Mississauga
06=Site 040 Mowat 40MOWT Toronto
07=Site 026 Sunderland 26SUND
08=Site 038 Pontypool 38PONT
09=Site 005 Ballinafad 05BALL
10=Site 007 Charlton 07CHAR Hamilton
11=Site 039 King City 39KING
12=Site 038 Pontypool 38PONT
13=Site 026 Sunderland 26SUND
14=Site 005 Ballinafad 05BALL
15=Site 007 Charlton 07CHAR Hamilton
16=Site 037 Whitby 37WHIT
17=Site 040 Mowat 40MOWT Toronto
18=Site 039 King City 39KING
19=Site 009 Britannia 09BRIT Mississauga
20=Site 007 Charlton 07CHAR Hamilton
21=Site 005 Ballinafad 05BALL
22=Site 037 Whitby 37WHIT
23=Site 026 Sunderland 26SUND
24=Site 037 Whitby 37WHIT
25=Site 007 Charlton 07CHAR Hamilton
26=Site 009 Britannia 09BRIT Mississauga
27=Site 039 King City 39KING
28=Site 037 Whitby 37WHIT
29=Site 005 Ballinafad 05BALL
30=Site 038 Pontypool 38PONT
31=Site 005 Ballinafad 05BALL
32=Site 007 Charlton 07CHAR Hamilton
33=Site 026 Sunderland 26SUND
34=Site 009 Britannia 09BRIT Mississauga
35=Site 040 Mowat 40MOWT Toronto
36=Site 009 Britannia 09BRIT Mississauga
37=Site 039 King City 39KING
38=Site 007 Charlton 07CHAR Hamilton
39=Site 037 Whitby 37WHIT
40=Site 026 Sunderland 26SUND
41=Site 038 Pontypool 38PONT
42=Site 040 Mowat 40MOWT Toronto
43=Site 039 King City 39KING
44=Site 039 King City 39KING
45=Site 009 Britannia 09BRIT Mississauga
46=Site 038 Pontypool 38PONT
47=Site 009 Britannia 09BRIT Mississauga
48=Site 007 Charlton 07CHAR Hamilton
49=Site 026 Sunderland 26SUND
50=Site 037 Whitby 37WHIT
51=Site 038 Pontypool 38PONT
52=Site 026 Sunderland 26SUND
53=Site 005 Ballinafad 05BALL
54=Site 009 Britannia 09BRIT Mississauga
55=Site 005 Ballinafad 05BALL
56=Site 040 Mowat 40MOWT Toronto
57=Site 039 King City 39KING
58=Site 039 King City 39KING
59=Site 007 Charlton 07CHAR Hamilton
60=Site 009 Britannia 09BRIT Mississauga
61=Site 040 Mowat 40MOWT Toronto
62=Site 009 Britannia 09BRIT Mississauga
63=Site 039 King City 39KING
64=Site 040 Mowat 40MOWT Toronto

[BANK43]
BANKNAME=Transportation Mississauga
00=First Student Canada 
01=The Cab Company
02=A Black Cab
03=Trott Transit
04=Switzer Carty  Long Bus 
05=A Black Cab
06=Switzer Carty  Short BusVans 
07=First Student Canada 
08=First Student Canada 
09=Golden Taxi
10=Blue  White Taxi
11=Attridge Transportation
12=Attridge Transportation
13=All Star Taxi

[BANK44]
BANKNAME=2 M Band
00=VE3YYZ DSTAR  Toronto
01=VE3WOO  Toronto
02=VA3GTU  Toronto
03=VE3OBN  Toronto
04=VE3GSR  King City
05=VE3YRA  King City
06=VE3CTV  Toronto
07=VE3TWR  Toronto
08=VE3MIS  Mississauga
09=VE3PYL  Mississauga
10=VE3ULR  Ballantrae
11=VE3WAS  King City
12=VE3RDP  Inglewood
13=VE3WIK  Carlisle
14=VA3RTC  Toronto
15=VE3NCF  Hamilton
16=VE3PRC Brampton
17=VE3RAE Burlington ARES Backup
18=VE3TOR  Toronto
19=VA3SUP  Whitby
20=VE3SKY  Toronto
21=VE3OAK  Oakville
22=VE3RSS  Acton
23=VE3RPT  Uxbridge
24=VE3OSH  Oshawa
25=VE3OD  Georgetown  Halton ARES
26=VE3WOM  Whitby
27=VE3YRK DSTAR
28=VE3MOT  Richmond Hill
29=VE3RSB  Burlington ARES
30=VE3YRC  Aurora
31=VE3TNC  Toronto
32=VA3BAL  Ballantrae
33=VE3PDX  Stoney Creek
34=VE3SPA  Pickering

[BANK45]
BANKNAME=Business Vaughan
00=Maloron Communications 
01=Astro Taxi COOP
02=Vaughan Mills  Security 
03=United Parcel Service  Trailers
04=United Parcel Service  Hub Control
05=Vaughan Mills  Property Management

[BANK46]
BANKNAME=Business School Buses
00=Cardinal 
01=Stock Transportation
02=Stock Transportation
03=Cardinal 
04=First Student Canada
05=Maloron Communications Leased  Dispatch
06=Maloron Communications Leased  Dispatch
07=Stock Transportation
08=First Student Canada
09=First Student Canada
10=McCluskey

[BANK47]
BANKNAME=Business Taxi
00=OnTime taxi
01=Crown Taxi
02=Beck Taxi subcontract for WheelTrans Cars
03=Able Atlantic Taxi
04=Able Atlantic Taxi
05=Metro Cab
06=Beck Taxi subcontract for WheelTrans Dispatch
07=Royal Taxi 
08=Beck Taxi subcontract for WheelTrans Cars
09=Beck Taxi 
10=AAA Best Choice Taxi
11=Beck Taxi
12=Beck Taxi subcontract for WheelTrans Cars
13=Crown Taxi
14=Beck Taxi
15=Beck Taxi subcontract for WheelTrans Cars
16=Crown Taxi 2 Bloor Street E
17=Beck Taxi  Central Dispatch  
18=Crown Taxi Inc
19=AAA Best Choice Taxi
20=COOP Cabs
21=5 Star Taxi
22=Beck Taxi  WheelTrans
23=Maple Leaf Cabs
24=City Taxi  Central Dispatch
25=Beck Taxi 
26=Beck Taxi 
27=Kingsboro Taxi 
28=Scarborough Taxi
29=Scarborough Taxi
30=ABC Ambassadors Taxi
31=Bee Line Taxi

[BANK48]
BANKNAME=Education Toronto District School Board
00=Second St Middle
01=Mowat CI
02=Rawlinson Community School
03=Rivercrest Junior School

[BANK49]
BANKNAME=Ontario Power Generation  Pickering
00=Ontario Power Generation  Paging 

[BANK50]
BANKNAME=Business Clarington
00=Bell Mobile Paging
01=Algoma Orchards
02=Dufferin Concrete
03=Student Transportation of Canada
04=Phoenix Transportation
05=First Student Canada
06=Canada Building Materials
07=Dufferin Concrete
08=Bowmanville Taxi
09=Petro Canada
10=Kobes Nurseries
11=St Marys Cement Plant
12=Student Transportation Services of Central Ontario
13=Williams Communications
14=WalMart Canada
15=Shoppers Drug Mart  Longworth
16=Covanta Durham York Renewable Energy
17=Cineplex Odeon

[BANK51]
BANKNAME=Business Oshawa
00=TaxiTaxi
01=Miller Paving
02=Morris Chemicals
03=City Wide Taxi
04=Bobs Towing
05=Durhamway School Bus
06=GenAuto Shippers

[BANK52]
BANKNAME=Whitby Hydro Energy Services Corporation
00=Whitby Hydro Energy Services Corporation

[BANK53]
BANKNAME=Golf Courses Burlington Golf and Country Club
00=Operations

[BANK54]
BANKNAME=Regionwide
00=Hamilton EMS  Paging
01=Hamilton EMS  Paging 
02=Fire Dispatch  Regional South
03=Fire Dispatch Trunk Simulcast
04=Hamilton Regional Conservation Authority
05=Region Plows
06=Region Plows
07=Hamilton Regional Conservation Authority
08=Durham Region Works Alarms

[BANK55]
BANKNAME=Media Rogers Communications
00=Traffic
01=Darryl Dahmer  Skymaster 1

[BANK56]
BANKNAME=Ontario Community Emergency Assistance Program
00=Ontario Community Emergency Assistance Program
01=Ontario Community Emergency Assistance Program
02=Ontario Community Emergency Assistance Program

[BANK57]
BANKNAME=Business Whitby
00=LocPipe
01=Pilgrim Transportation Services
02=Dufferin Concrete
03=Circle Taxi
04=Liquor Control Board Ontario  Durham Warehouse Ch 1 
05=Liquor Control Board Ontario  Durham Warehouse Ch 2
06=Liquor Control Board Ontario  Durham Warehouse Ch 3
07=Liquor Control Board Ontario  Durham Warehouse Ch 4
08=Atlantic Packaging

[BANK58]
BANKNAME=Bolton
00=Peel Regional Road 50 Weigh Scales 

[BANK59]
BANKNAME=Business Brock Township
00=Canada Building Materials

[BANK60]
BANKNAME=African Lion Safari African Lion Safari
00=Tour Guides  Wardens
01=Channel 2
02=Channel 1  Main
03=Koho Food Services
04=Safari Outfitters
05=Operations

[BANK61]
BANKNAME=Hamilton General
00=Cardiac Ward Paging
01=Security

[BANK62]
BANKNAME=Attractions The Clarington Family Outdoor Adventure Park
00=The Clarington Family Outdoor Adventure Park
01=Bowmanville Zoo 

[BANK63]
BANKNAME=  MetroNET
00=Site 001 MetroNET

[BANK64]
BANKNAME=Business Construction
00=Dufferin Concrete 
01=Dufferin Concrete
02=Dufferin Concrete 
03=Canadian Building Materials
04=Innocon Concrete  Mississauga Yard 
05=Innocon Concrete  Data
06=Teskey Construction 
07=CBM Concrete
08=Daniels
09=Amherst Crane Rental
10=Stacey Electric 
11=Metrix Ready Mix
12=AECON
13=Daniels

[BANK65]
BANKNAME=Business Waterdown
00=Connon Nurseries Ch 1
01=Connon Nurseries Ch 2
02=Connon Nurseries Ch 3
03=BrennBFarms  Westover
04=Attridge Transportation

[BANK66]
BANKNAME=Toronto Transit Commission
00=Streetcar Maintenance of Way
01=Security Simplex
02=Surface Ch1 Transit Control
03=Surface Ch2 WheelTrans
04=Surface Ch3 
05=RT Yard
06=Surface Ch 4 
07=Surface Ch5 Streetcars
08=RT Line
09=Surface Ch6 SubwaySRT Yard
10=Surface Ch7 Subway Maintenance

[BANK67]
BANKNAME=Media Bell Media Queen Street Bureau
00=CTV CP24  Mobile Link
01=CP24  Wireless
02=CP24  Wireless 
03=CP24  Wireless 
04=CP24  Wireless 
05=CP24  Wireless 
06=CP24  Wireless 
07=CP24  Wireless

[BANK68]
BANKNAME=Attractions Live Nation
00=Food and Beverage  Warehouse 
01=Guest Services
02=Food and Beverage
03=Food and Beverage  Venue

[BANK69]
BANKNAME=Business Hamilton
00=Sharp Bus Lines
01=Kenneth R Awrey
02=Dufferin Concrete
03=Caledonia Transportation
04=Caledonia Transportation
05=Lafarge Paving and Costruction
06=Dufferin Concrete
07=Dufferin Concrete
08=Jackson Square Mall
09=Jackson Square Mall
10=Jackson Square Mall
11=Cineplex  Silvercity Ancaster 
12=Limeridge Mall  Security
13=Bunge Canada  Maintenance
14=Caledonia Transportation
15=Cardi Construction
16=Hamilton Cab 
17=Eastgate Square
18=ArcelorMittal Dofasco  Fire and EMS
19=The Centre on Barton  Security
20=ArcelorMittal Dofasco  Security
21=Yellow Cab Company
22=First Response Environmental
23=Empire Jackson Square 6 Theatres

[BANK70]
BANKNAME=  Horizon Utilities Corporation 
00=Site 001 Hamilton
01=Site 001 Hamilton

[BANK71]
BANKNAME=McMaster University
00=Maintenance
01= Reactor

[BANK72]
BANKNAME=Hamilton
00=Work Channel
01=Horizon Utilities

[BANK73]
BANKNAME=Oshawa PUC Networks
00=Oshawa PUC Networks
01=Oshawa PUC Networks  Simplex

[BANK74]
BANKNAME=Richmond Hill
00=Central York Fire Service  Paging
01=Works Operations
02=B1  Fire  Emergency Services  Simplex 
03=B16   Fire Repeater B

[BANK75]
BANKNAME=Townships of Brock Scugog Town of Uxbridge Fire Services
00=North Durham Region Fire  Paging

[BANK76]
BANKNAME=  Caledon Town
00=Site 001 Concession 6
01=Site 001 Concession 6

[BANK77]
BANKNAME=Milton
00=Fire Dispatch 
01=Maplehurst Correctional Complex
02=Hydro
03=Vanier Centre For Women Maplehurst
04=Fire Dispatch  UHF link
05=Kelso Conservation Area
06=Rattlesnake Point Conservation Area
07=Halton Region Waste Management

[BANK78]
BANKNAME=Halton Hills
00=Town Fire Department
01=Hydro

[BANK79]
BANKNAME=Burlington
00=Fire Dispatch  Simulcast
01=Hydro
02=OPP Rebroadcast

[BANK80]
BANKNAME=Business Pickering
00=Royal Ashburn Golf Club
01=Dufferin Concrete
02=Dufferin Ready Mix
03=Student Transportation of Canada

[BANK81]
BANKNAME=Business Various
00=Town II Condominium  Property Management 
01=Locus Electric 
02=Toronto Ontario Temple  The Church of Jesus Christ of Latterday Saints
03=Freemont Landscaping
04=TST Overland Express

[BANK82]
BANKNAME=Business Newmarket
00=Switzer Carty Bus
01=Stock Transportation
02=Upper Canada Mall 
03=Best Buy
04=Michaels
05=Upper Canada Mall  Security
06=Silver City Theatre
07=York District School Board

[BANK83]
BANKNAME=City Services
00=Hamilton Port Authority
01=Hamilton Port Authority  GPS location data
02=Hamilton Street Railway Dispatch
03=Hamilton Street Railway  Supervisors
04=Waste Management
05=Hamilton Street Railway
06=Hamilton Street Railway
07=City Parking Enforcement
08=Police Simplex
09=ERU Simplex
10=Fire  Simplex
11=Works  Traffic  Simplex

[BANK84]
BANKNAME=Region Wide
00=Dispatch  MississaugaBrampton and Caledon
01=Municipal Works Dept
02=MOH Base Station Paging
03=York Region District School Board

[BANK85]
BANKNAME=Retail Mississauga
00=Lowes  5348 Mavis Road
01=Dixie Outlet Mall  Security 
02=Dixie Outlet Mall  Maintenance
03=Heartland Town Centre  Michaels
04=Winston Argentia Centre  Best Buy
05=Square One  Microsoft Store
06=Heartland Town Centre  Old Navy
07=Erin Mills Town Centre  Old Navy
08=Square One  Property Management 
09=Square One  Security
10=Meadowvale Town Centre 
11=Heartland Town Centre  Best Buy
12=Erin Mills Town Plaza  HomeSense
13=Costco  3180 Laird Road
14=Winston Argentia Centre  Bed Bath and Beyond
15=National Sports  2921 Eglinton AveWest

[BANK86]
BANKNAME=Vaughan
00=Vaughan Parks Joint Operations Centre
01=Vaughan Works Joint Operations Centre
02=A1  Fire  Rescue   Simplex
03=A16  Fire Repeater A
04=Expertech onsite Joint Operations Centre

[BANK87]
BANKNAME=Government of Canada
00=Industry Canada

[BANK88]
BANKNAME=Business Couriers
00=Jesk Enterprises Ltd
01=TransOntario Express
02=Flying Dutchman
03=Arrowspeed Delivery
04=DKR Courier Service
05=United Messengers 
06=Golden Arrow Courier

[BANK89]
BANKNAME=  Talk Wireless LTR VHF Hamilton
00=Site 001 Confirmed LCN
01=Site 001 Confirmed LCN
02=Site 001 Confirmed LCN

[BANK90]
BANKNAME=Business Cranston
00=Caledonia Transportation 

[BANK91]
BANKNAME=Business Dundas
00=Carmeuse Lime and Stone

[BANK92]
BANKNAME=Business Airport Taxi and Limousine
00=Aerofleet Taxi
01=Airflight Service
02=Aerofleet Taxi
03=Airline Limousine
04=Aeroport Taxi
05=Aircab

[BANK93]
BANKNAME=Business Milton
00=Union Gas 
01=Oak Concrete 
02=CoSteel Recycling
03=CoSteel Recycling
04=Dufferin Aggregates
05=Dufferin Aggregates
06=A Black Cab

[BANK94]
BANKNAME=Business Lynden
00=Joost AH Dr Blieck Josnar Acres

[BANK95]
BANKNAME=  Telequip Systems King City
00=Site 001 King City
01=Site 001 King City
02=Site 001 King City

[BANK96]
BANKNAME=Business Bradford
00=Parkview Transit 

[BANK97]
BANKNAME=Business Limehouse
00=Fred J Anthony   Agricultural Chemicals

[BANK98]
BANKNAME=Business Vinemount
00=Waterford Sand and Gravel

[BANK99]
BANKNAME=  Yorkdale Shopping Centre
00=Site 001 Yorkdale
01=Site 001 Yorkdale

[BANK100]
BANKNAME=Attractions North York
00=Ontario Science Centre  Security

[BANK101]
BANKNAME=Scugog Township
00=Township Roads Dept 

[BANK102]
BANKNAME=Business Richmond Hill
00=Stock Transportation
01=Advance Unique Taxi

[BANK103]
BANKNAME=Business Ancaster
00=First Student Canada

[BANK104]
BANKNAME=Oakville REACT
00=Special Events

[BANK105]
BANKNAME=Pickering
00=Engineering  Public Works

[BANK106]
BANKNAME=Aurora
00=Town Works Dept

[BANK107]
BANKNAME=Markham
00=Town Works Dept
01=C1  Fire  Emergency Services  Simplex
02=C16  Fire Repeater C

[BANK108]
BANKNAME=Business Westover
00=BrennBFarms

[BANK109]
BANKNAME=Volunteer Organizations Special Events
00=Respond Search and Rescue

[BANK110]
BANKNAME=Business Ajax
00=Innocon Inc
01=First Student Canada

[BANK111]
BANKNAME=Business Flamborough
00=Airway Transit Service
01=Airways Transit Services

[BANK112]
BANKNAME=Business Uxbridge Township
00=Stock Transportation

[BANK113]
BANKNAME=Business Woodbridge
00=National Golf Club of Canada 

[BANK114]
BANKNAME=Event Medical Services
00=Spectrum Event Medical Services
01=Spectrum Event Medical Services
02=Spectrum Event Medical Services  on site

[BANK115]
BANKNAME=125 M Band
00=VE3RSD  Oakville
01=VE3RSD  Brampton  IRLP 
02=VA3WHQ  SSPBD Network
03=VE3WIK  Hamilton
04=VE3RSD  Mississauga  IRLP
05=VE3PAQ  Acton
06=VE3RSB  Burlington
07=VE3BEG  Uxbridge
08=VE3WIK  Carlisle

[BANK116]
BANKNAME=Veridian Connections
00=Veridian Connections Paging  
01=Veridian Connections Operations
02=Veridian Connections Paging 

[BANK117]
BANKNAME=Business Etobicoke
00=Swifttrans Airport Shuttle
01=Holiday Inn  Airport
02=CBRE Facilities Management  Resources Road Complex 
03=CF Sherway Gardens  Property Management
04=Albion Centre
05=CF Sherway Gardens  Security
06=Woodbine Centre  Security
07=Woodbine Centre  Property Management
08=Plant World
09=Cloverdale Mall
10=Home Depot  1983 Kipling Ave

[BANK118]
BANKNAME=Peel Region Attractions Powerade Centre
00=Centre 1
01=Centre 2
02=Centre 3
03=Centre 4

[BANK119]
BANKNAME=Markham 
00=Markham Stouffville Hospital  Security
01=Markham Stouffville Hospital  Maintenance

[BANK120]
BANKNAME=  Ryerson University
00=Site 001 Ryerson
01=Site 001 Ryerson
02=Site 001 Ryerson

[BANK121]
BANKNAME=  Metrolinx  GO Transit
00=Site 001 East Simulcast
01=Site 001 East Simulcast
02=Site 006 Uxbridge
03=Site 001 East Simulcast
04=Site 001 East Simulcast
05=Site 002 West Simulcast
06=Site 006 Uxbridge
07=Site 002 West Simulcast
08=Site 001 East Simulcast
09=Site 001 East Simulcast
10=Site 001 East Simulcast
11=Site 001 East Simulcast
12=Site 002 West Simulcast
13=Site 001 East Simulcast
14=Site 002 West Simulcast
15=Site 001 East Simulcast
16=Site 002 West Simulcast
17=Site 001 East Simulcast
18=Site 002 West Simulcast
19=Site 002 West Simulcast
20=Site 006 Uxbridge

[BANK122]
BANKNAME=  McMaster University
00=Site 001 MAC
01=Site 001 MAC
02=Site 001 MAC
03=Site 001 MAC
04=Site 001 MAC

[BANK123]
BANKNAME=  Alectra Utilities
00=Site 005 Markham
01=Site 006 Richmond Hill
02=Site 004 Vaughan

[BANK124]
BANKNAME=Business North York
00=CBRE Facilities Management  Wilson Complex  Ministry of Transportation 
01=Holiday Inn  Yorkdale  Housekeeping Paging
02=The Oaks  Property Management  Chalkfarm Drive
03=Fairview Mall
04=JaneFinch Mall
05=Lawrence Square Mall
06=Toronto Emergency Services  4300 Dufferin St  Maintenance
07=Shops at Don Mills
08=Fairview Mall  Property Management

[BANK125]
BANKNAME=Business Downtown
00=CBRE Facilities Management  Mowat Block
01=City of Toronto Properties  Security Ch 1
02=Union Station  Security Office
03=City of Toronto Properties  Security Ch 2
04=VIA Rail Canada  Union Station Porters
05=KoolHaus
06=Delta Chelsea Hotel
07=Hazelton Lanes
08=Sheraton Centre
09=Hotel InterContinental
10=77 Bloor Street West  Property Management
11=The Crossways  Property Management
12=Cumberland Terrace  Security
13=2 Bloor Street West  Property Management
14=Cumberland Terrace  Property Management
15=Commerce Court Ch 2
16=Richmond  Adelaide Centre  Property Management
17=Atrium On Bay  Security
18=Four Seasons Hotel
19=Delta Chelsea Hotel
20=Commerce Court Ch 1
21=Town Inn Suites
22=Atrium on Bay  Property Management
23=2 Bloor Street East
24=Carlton Tower
25=Royal Bank Plaza  Security
26=ShangriLa Hotel  Security

[BANK126]
BANKNAME=Attractions Core
00=Royal Ontario Museum  City of Toronto Security
01=Harbourfront Centre
02=Art Gallery of Ontario 
03=YongeDundas Square  Security Simplex 2
04=Harbourfront Centre
05=Metro Toronto Convention Centre Security
06=Metro Toronto Convention Centre Shuttle
07=Harbourfront Centre
08=YongeDundas Square  Security 
09=YongeDundas Square  Security Simplex 1 

[BANK127]
BANKNAME=  The Hospital For Sick Children
00=Site 001 HSC

[BANK128]
BANKNAME=Ontario Power Generation  Darlington
00=Ontario Power Generation  Darlington 

[BANK129]
BANKNAME=Ontario Power Generation
00=OPG  800 Kipling Avenue

[BANK130]
BANKNAME=  Toronto South Detention Centre
00=Site 001 Toronto South DC
01=Site 001 Toronto South DC
02=Site 001 Toronto South DC

[BANK131]
BANKNAME=Uxbridge 
00=Town Roads Department

[BANK132]
BANKNAME=Oakville
00=Hydro Ch 1  TG 100
01=Hydro Ch 2  Stringing
02=Works Department
03=Parks  Rec
04=The Marquee  Bouncer Office
05=Oakville Trafalgar Memorial Hospital 
06=The Marquee  Low Power
07=The Marquee  Bouncer Talkaround
08=Syl Apps Youth Treatment Centre  Kinark Services
09=Oakville Trafalgar Memorial Hospital 

[BANK133]
BANKNAME=  KELCOM Toronto
00=Site 001 CN Tower
01=Site 001 CN Tower
02=Site 001 CN Tower

[BANK134]
BANKNAME=  FleetConnect 
00=Site 012 Toronto
01=Site 011 Hamilton
02=Site 011 Hamilton
03=Site 011 Hamilton
04=Site 010 Milton
05=Site 010 Milton
06=Site 010 Milton
07=Site 012 Toronto
08=Site 014 Blackstock
09=Site 014 Blackstock
10=Site 012 Toronto
11=Site 013 King City
12=Site 013 King City
13=Site 012 Toronto
14=Site 014 Blackstock
15=Site 014 Blackstock
16=Site 013 King City

[BANK135]
BANKNAME=Correctional Facilities
00=Toronto East Detention Centre

[BANK136]
BANKNAME=Ontario Government Agencies
00=Hamilton Wentworth Detention Centre
01=Hamilton Wentworth Detention Centre

[BANK137]
BANKNAME=Newmarket
00=Newmarket  Tay Power Distribution
01=Town Public Works Dept

[BANK138]
BANKNAME=McMaster University Medical Centre
00=Security and Parking
01=Security and Parking

[BANK139]
BANKNAME=Ontario Shores Centre for Mental Health Sciences
00=Ontario Shores Centre for Mental Health Sciences
01=Ontario Shores Centre for Mental Health Sciences
02=Ontario Shores Centre for Mental Health Sciences
03=Ontario Shores Centre for Mental Health Sciences  Paging

[BANK140]
BANKNAME=Brampton
00= Roy McMurtry Youth Centre 
01=Corporate Properties
02=Corporate Properties
03=Corporate Properties
04=Corporate Properties
05=Corporate Properties
06=Brampton Civic Hospital  Portering
07=Brampton Civic Hospital  Housekeeping
08=Brampton Civic Hospital  Security

[BANK141]
BANKNAME=Toronto Hydro Electric System
00=Toronto Hydro Electric System  Underground

[BANK142]
BANKNAME=Caledon Fire  Emergency Services
00=Fire  Station 302 Dispatch

[BANK143]
BANKNAME=Mississauga Fire Service
00=Station Dispatch
01=Talkaround
02=Talkaround
03=Talkaround
04=Talkaround
05=Vehicular Repeater

[BANK144]
BANKNAME=  Fairmont Royal York Hotel
00=Site 001 Royal York Hotel
01=Site 001 Royal York Hotel
02=Site 001 Royal York Hotel
03=Site 001 Royal York Hotel

[BANK145]
BANKNAME=  Suncor Energy Mississauga
00=Site 001 Suncor Energy
01=Site 001 Suncor Energy
02=Site 001 Suncor Energy
03=Site 001 Suncor Energy

[BANK146]
BANKNAME=  OLGC  Woodbine Racetrack Slots
00=Site 001 OLGC Woodbine
01=Site 001 OLGC Woodbine
02=Site 001 OLGC Woodbine
03=Site 001 OLGC Woodbine

[BANK147]
BANKNAME=  OnQue
00=Site 003 Hamilton
01=Site 003 Hamilton
02=Site 003 Hamilton
03=Site 003 Hamilton
04=Site 003 Hamilton
05=Site 001 CN Tower
06=Site 001 CN Tower
07=Site 001 CN Tower
08=Site 004 Clarington
09=Site 007 Scarborough
10=Site 001 CN Tower
11=Site 001 CN Tower
12=Site 001 CN Tower
13=Site 001 CN Tower
14=Site 008 Aurora
15=Site 001 CN Tower
16=Site 001 CN Tower
17=Site 001 CN Tower
18=Site 001 CN Tower
19=Site 004 Clarington
20=Site 006 Milton
21=Site 001 CN Tower
22=Site 001 CN Tower
23=Site 001 CN Tower
24=Site 001 CN Tower
25=Site 008 Aurora
26=Site 007 Scarborough
27=Site 001 CN Tower
28=Site 001 CN Tower
29=Site 001 CN Tower
30=Site 001 CN Tower
31=Site 008 Aurora
32=Site 006 Milton
33=Site 001 CN Tower
34=Site 006 Milton
35=Site 004 Clarington

[BANK148]
BANKNAME=  Rogers Centre
00=Site 001 001
01=Site 001 001
02=Site 001 001
03=Site 001 001
04=Site 001 001

[BANK149]
BANKNAME=  Talk Wireless LTR UHF
00=Site 001 Hamilton

[BANK150]
BANKNAME=  RCMP O Division
00=Site 036 Ballantrae
01=Site 016 Toronto  West 
02=Site 017 Toronto  East
03=Site 035 Hamilton
04=Site 041 Clarington
05=Site 004 Newmarket
06=Site 024 Toronto  South
07=Site 041 Clarington
08=Site 016 Toronto  West 
09=Site 004 Newmarket
10=Site 023 Airway Centre  Toronto Pearson Airport
11=Site 035 Hamilton
12=Site 023 Airway Centre  Toronto Pearson Airport
13=Site 041 Clarington
14=Site 024 Toronto  South
15=Site 035 Hamilton
16=Site 017 Toronto  East
17=Site 016 Toronto  West 
18=Site 024 Toronto  South
19=Site 027 Milton
20=Site 035 Hamilton
21=Site 023 Airway Centre  Toronto Pearson Airport
22=Site 016 Toronto  West 
23=Site 009 King City
24=Site 027 Milton
25=Site 009 King City
26=Site 027 Milton
27=Site 017 Toronto  East
28=Site 023 Airway Centre  Toronto Pearson Airport
29=Site 009 King City
30=Site 024 Toronto  South
31=Site 017 Toronto  East

[BANK151]
BANKNAME=  Mobile Business  Toronto LTR  B
00=Site 001 2 Bloor St E
01=Site 001 2 Bloor St E
02=Site 001 2 Bloor St E
03=Site 001 2 Bloor St E
04=Site 001 2 Bloor St E
05=Site 001 2 Bloor St E

[BANK152]
BANKNAME=  Mobile Business  Hamilton 420 MHz
00=Site 001 Confirmed LCN
01=Site 001 Confirmed LCN
02=Site 001 Confirmed LCN
03=Site 001 Confirmed LCN
04=Site 001 Confirmed LCN
05=Site 001 Confirmed LCN
06=Site 001 Confirmed LCN

[BANK153]
BANKNAME=  Toronto Transit Commission PowerTrunk
00=Site 001 Toronto
01=Site 001 Toronto
02=Site 001 Toronto
03=Site 001 Toronto
04=Site 001 Toronto
05=Site 001 Toronto
06=Site 001 Toronto
07=Site 001 Toronto
08=Site 001 Toronto
09=Site 001 Toronto
10=Site 001 Toronto
11=Site 001 Toronto

[BANK154]
BANKNAME=  Point to Point
00=Site 002 King City
01=Site 002 King City
02=Site 002 King City

[BANK155]
BANKNAME=TTC  CIS 
00=22  CN Tower
01=33  Finch 
02=35  Arrow 
03=36  Malvern
04=37  Hillcrest 
05=38  Greenwood 
06=39  Wilson 
07=40  Pharmacy
08=41  Shipp
09=42  Birchmount 
10=43  Davisville

[BANK156]
BANKNAME=  DMRMARC Ontario Amateur Repeater Network
00=Site 302321 VA3XFT Toronto
01=Site 302319 VE3OBI Raglan
02=Site 302303 VA3XPR Toronto
03=Site 302315 VE3UHM Hamilton

[BANK157]
BANKNAME=70 cm Band
00=VE3ULR  Aurora
01=VE3RPT  Uxbridge
02=VE3PAQ  Acton
03=VA3UKW  Toronto
04=VA3ODX  Burlington  Echolink
05=VA3CTR  Unionville
06=VE3HAL  Milton
07=VA3GTU  Toronto
08=VE3OKR  Oakville
09=VA3URU  Ballantrae
10=VE3RDM  Hamilton
11=VE3UHM  Hamilton
12=VE3GIV  Hamilton
13=VE3CAY  Toronto
14=VA3GTU  Toronto
15=VE3YYZ   DSTAR  Toronto
16=VE3WOO  Toronto
17=VA3GTU  Etobicoke
18=VA3GTU  Etobicoke
19=VA3GTU  Acton
20=VE3SNM  Ballantrae
21=VA3GTU  Toronto
22=VE3NAA  Oshawa
23=VA3SCR  Toronto
24=VE3YYZ  Toronto
25=VE3ZOE  Hamilton
26=VE3SKI  Toronto
27=VE3RAK  Toronto
28=VE3BUR  Burlington
29=VA3BUR  Southwest  Aldershot  Hamilton 
30=VE3RFI
31=VA3PWR  Newmarket
32=VE3VOP  Toronto
33=VE3RTC  Scarborough
34=VA3HR  Milton  Halton ARES
35=VE3WOM  Whitby
36=VE3NIB  Toronto
37=VE3PRC  Brampton
38=VE3UPR
39=VE3NOR  Toronto
40=VE3WIK  Carlisle
41=VA3BAL  Ballantrae
42=VA3GTU  Scarborough
43=VE3JOP  Vaughan
44=VA3PMO  Mississauga
45=VA3TVB  Scarborough
46=VE3OBN   Toronto
47=VE3ZRB  Halton Hills
48=VE3UHM  Hamilton DMR
49=VE3NCF  Hamilton
50=VE3WDX  Aurora
51=VE3WOO  Caledon
52=VE3YRC  Richmond Hill
53=VE3OAK  Oakville 
54=VE3WOQ  Whitby
55=VE3TWR  Toronto
56=VA3BMI  Toronto
57=VE3URU  Toronto
58=VE3YRK DSTAR
59=VE3OBI  Raglan
60=VE3MIS  Mississauga
61=VE3DAX  Pickering
62=VA3ATL  Toronto
63=VE3RSB  Burlington 
64=VE3UKW  Toronto
65=VA3OPR  Brampton

[BANK158]
BANKNAME=  BrandMeister Canada Amateur Repeater Network
00=Site 302327 VE3OUR Durham
01=Site 302321 VE3YYZ Toronto

[BANK159]
BANKNAME=Media Oshawa
00=CKDO Studio Link

[BANK160]
BANKNAME=Media Shaw Media
00=Global News Helicopter CFMTE

[BANK161]
BANKNAME=Mississauga
00=Community Centre Operations Ch1 
01=Gordon Graydon Memorial SS  Ch 1 Administration
02=StGonzaga Secondary SchoolErin Meadows Community Centre
03=Community Centre Operations Ch2
04=Gordon Graydon Memorial SS  Ch 2 MaintenanceCustodial

[BANK162]
BANKNAME=  Mobile Business Communications 
00=Site 001 CN Tower
01=Site 001 CN Tower
02=Site 001 CN Tower
03=Site 001 CN Tower
04=Site 001 CN Tower
05=Site 001 CN Tower

[BANK163]
BANKNAME=  Purolator
00=Site 001 Ontario Hub
01=Site 001 Ontario Hub
02=Site 001 Ontario Hub

[BANK164]
BANKNAME=  GOTRBO Network
00=Site 011 Fennell
01=Site 007 CN Tower
02=Site 007 CN Tower
03=Site 004 Ballantrae
04=Site 006 Clarington
05=Site 006 Clarington
06=Site 004 Ballantrae
07=Site 007 CN Tower
08=Site 011 Fennell
09=Site 011 Fennell
10=Site 007 CN Tower
11=Site 007 CN Tower

[BANK165]
BANKNAME=FirstOntario Centre Operations
00=Operations
01=Centre Events
02=FirstOntario TG 2
03=FirstOntario TG 4
04=HP Events
05=FirstOntario TG 3
06=Administration
07=HP Stage
08=Emergency
09=Bulldogs
10=Dispatch

[BANK166]
BANKNAME=Attractions Etobicoke
00=Woodbine Race Track  Champions 
01=OLG Slots Security 
02=Woodbine Race Track  Maintenance 
03=Woodbine Race Track  Officials
04=Woodbine Race Track  Guest Services

[BANK167]
BANKNAME=  Metro Toronto Convention Centre
00=Site 001 MTCC
01=Site 001 MTCC

[BANK168]
BANKNAME=Business Scarborough
00=Malvern Town Centre
01=Parkway Mall
02=The Greens at Tam OShanter  Condo Security

[BANK169]
BANKNAME=  OLGC  Mohawk Racetrack Slots
00=Site 001 Site 1
01=Site 001 Site 1

[BANK170]
BANKNAME=Environment Canada 4905 Dufferin Street
00=In House  Security
01=In House  Emergency

[BANK171]
BANKNAME=Federal Offices Hamilton
00=CRA Security
01=CRA Security 
02=EC  Canadian Centre Inland Waters
03=EC  Canadian Centre Inland Waters

[BANK172]
BANKNAME=  University of Toronto
00=Site 001 55 Harbord Street
01=Site 001 55 Harbord Street
02=Site 001 55 Harbord Street

[BANK173]
BANKNAME=Hatzoloh Toronto 
00=Dispatch

[BANK174]
BANKNAME=Healthcare North York Branson Urgent Care 
00=Maintenance
01=Security

[BANK175]
BANKNAME=Healthcare Scarborough Hospital  General and Grace sites 
00=Security
01=Maintenance
02=Security

[BANK176]
BANKNAME=Flamboro Downs Slots Flamborough
00=Slot Technicians
01=Emergency
02=Track Security
03=Food Service
04=Valet
05=Customer Service

[BANK177]
BANKNAME=Healthcare Sunnybrook Health Sciences Centre
00=Security 2
01=Security 1

[BANK178]
BANKNAME=West 5th Campus
00=Security

[BANK179]
BANKNAME=  National Communications Site Services DMR
00=Site 002 Area 2
01=Site 000 Area 0
02=Site 000 Area 0
03=Site 002 Area 2

[BANK180]
BANKNAME=  Sheridan College Oakville
00=Site 001 Sheridan

[BANK181]
BANKNAME=  Maple Lodge Farms
00=Site 001 Brampton
01=Site 001 Brampton
02=Site 001 Brampton

[BANK182]
BANKNAME=Business Thornhill
00=Glen Park Apartments  Property Maintenance 
01=Glen Park Apartments  Property Security
02=The Promenade  Security 

[BANK183]
BANKNAME=  Humber College
00=Site 001 North Campus
01=Site 001 North Campus
02=Site 001 North Campus

[BANK184]
BANKNAME=Healthcare Holland Bloorview Childrens Rehabilitaion Centre
00=Operations

[BANK185]
BANKNAME=Education Clarington
00=Charles Bowman Public School
01=St Elizabeth Catholic School
02=John M James Public School
03=Harold Longworth Public School
04=St Stephen Catholic Secondary School

[BANK186]
BANKNAME=Canadas Wonderland Vaughan
00=Ch 9  Speedcity Raceway
01=Ch 4  Entertainment Theatre Group Sales Administration Marketing Finance
02=Ch 1  Park Safety and Security
03=Ch 2  Attractions Maintenance Ecology and Utility
04=Ch 3  Resale and Admissions

[BANK187]
BANKNAME=Healthcare Michael Garron Hospital
00=Security 
01=Security 

[BANK188]
BANKNAME=Attractions Oshawa Ski Club
00=BrimacombeOshawa Ski Club Ch 2
01=BrimacombeOshawa Ski Club Ch 3
02=BrimacombeOshawa Ski Club Ch 1

[BANK189]
BANKNAME=  National Communications Site Services Motorola
00=Site 001 Site1
01=Site 001 Site1
02=Site 001 Site1

[BANK190]
BANKNAME=  ICOM Canada 
00=Site 009 Hamilton
01=Site 009 Hamilton
02=Site 003 Toronto
03=Site 003 Toronto
04=Site 003 Toronto
05=Site 009 Hamilton
06=Site 004 Ballantrae

[BANK191]
BANKNAME=Mohawk College
00=Security

[BANK192]
BANKNAME=Healthcare North York General
00=Security

[BANK193]
BANKNAME=  University Health Network  Toronto General Hospital
00=Site 001 Toronto General Hospital

[BANK194]
BANKNAME=Golf and Country Clubs Hamilton Golf and Country Club
00=Security  Fairway Grooming

[BANK195]
BANKNAME=  Porter Airlines
00=Site 001 Billy Bishop Toronto Island Airport
01=Site 001 Billy Bishop Toronto Island Airport

[BANK196]
BANKNAME=  CF Toronto Eaton Centre
00=Site 001 Eaton Centre
01=Site 001 Eaton Centre

[BANK197]
BANKNAME=Golf Beacon Hall Golf Club
00=Gatehouse and Valet
01=Operations

[BANK198]
BANKNAME=  Ritz Carlton Hotel
00=Site 001 Ritz Carlton Hotel
01=Site 001 Ritz Carlton Hotel
02=Site 001 Ritz Carlton Hotel
03=Site 001 Ritz Carlton Hotel

[BANK199]
BANKNAME=  Oshawa Centre
00=Site 001 Oshawa Centre

[BANK200]
BANKNAME=  FedEx Pearson International Distribution
00=Site 001 FedEx PIA
01=Site 001 FedEx PIA
02=Site 001 FedEx PIA
03=Site 001 FedEx PIA

[BANK201]
BANKNAME=  Toronto Zoo
00=Site 001 Toronto Zoo
01=Site 001 Toronto Zoo
02=Site 001 Toronto Zoo

[BANK202]
BANKNAME=Education York University
00=Keele Campus Security 
01=Keele Campus Security 
02=Seneca  York  Campus Security
03=Glendon Campus Security 
04=Keele Campus Parking Enforcement

[BANK203]
BANKNAME=  Pickering Town Centre
00=Site 001 PTC

[BANK204]
BANKNAME=  Federal Marine Terminals
00=Site 001 Terminal

[BANK205]
BANKNAME=Education Ontario College of Art and Design
00=Operations
01=Security

[BANK206]
BANKNAME=  Communitronics
00=Site 001 Confirmed LCN
01=Site 001 Confirmed LCN

[BANK207]
BANKNAME=Healthcare St Michaels Hospital
00=Security

[BANK208]
BANKNAME=Healthcare Rouge Valley  Centennary Hospital
00=Security

[BANK209]
BANKNAME=Attractions Great Blue Heron Charity Casino  Port Perry
00=Great Blue Heron Charity Casino F2
01=Great Blue Heron Charity Casino F3
02=Great Blue Heron Charity Casino F1
03=Great Blue Heron Charity Casino F4

[BANK210]
BANKNAME=Peel Region Attractions Hershey Centre
00=Channel 2
01=Channel 1
02=Channel 3
03=Channel 4

[BANK211]
BANKNAME=Attractions Jungle Cat World Wildlife Park
00=Jungle Cat World Wildlife Park

[BANK212]
BANKNAME=Media Canadian Broadcasting Corporation  Broadcast Centre
00=CBC News

[BANK213]
BANKNAME=  Ford Motor Company Oakville 
00=Site 001 Oakville
01=Site 001 Oakville
02=Site 001 Oakville
03=Site 001 Oakville

[BANK214]
BANKNAME=Attractions Scarborough
00=Security Backup
01=Toronto Zoo  Simplex

[BANK215]
BANKNAME=  Trillium Health Partners
00=Site 003 Mississauga Hospital
01=Site 003 Credit Valley Hospital 

[BANK216]
BANKNAME=  Sheridan College Peel Region
00=Site 002 Hazel McCallion Campus
01=Site 001 Davis Campus

[BANK217]
BANKNAME=  Magna Karmax 
00=Site 001 Milton
01=Site 001 Milton

[BANK218]
BANKNAME=  Billy Bishop Toronto City Airport
00=Site 001 Toronto Island
01=Site 001 Toronto Island

[BANK219]
BANKNAME=Juravinski Hospital
00=Juravinski Hospital 
01=Juravinski Hospital  Security
02=Juravinski Hospital  Security

[BANK220]
BANKNAME=  Exhibition Place
00=Site 001 Exhibition Place
01=Site 001 Exhibition Place
02=Site 001 Exhibition Place
03=Site 001 Exhibition Place

[BANK221]
BANKNAME=  CRH Canada  Holcim
00=Site 001 Mississauga

[BANK222]
BANKNAME=  OLGC  Ajax Downs Racetrack Slots
00=Site 001 Ajax Downs
01=Site 001 Ajax Downs

[BANK223]
BANKNAME=Chedoke Campus
00=Chedoke Campus  Security

[BANK224]
BANKNAME=Retail Brampton
00=Shoppers World Ch 1
01=Shoppers World Ch 2

[BANK225]
BANKNAME=  Honeywell Aerospace
00=Site 001 Mississauga
01=Site 001 Mississauga
02=Site 001 Mississauga

[BANK226]
BANKNAME=  Erin Mills Town Center
00=Site 001 Erin Mills
01=Site 001 Erin Mills

[BANK227]
BANKNAME=  Fleetcom DMR
00=Site 001 500 Duplex
01=Site 001 500 Duplex
02=Site 001 500 Duplex

[BANK228]
BANKNAME=Peel Region Attractions Meadowvale Theatre
00=Medowvale Theatre

[BANK229]
BANKNAME=Attractions Rogers Centre
00=Stadium  Roof Control
01=Stadium  Roof Control

[BANK230]
BANKNAME=Business Canada Computers
00=Red
01=Yellow
02=Green
03=Blue

[BANK231]
BANKNAME=  Manheim Auto Auctions
00=Site 001 Milton
01=Site 001 Milton

[BANK232]
BANKNAME=Business Armoured Car Transportation
00=Brinks Canada Armoured Cars

[BANK233]
BANKNAME=  Roxul
00=Site 001 Milton
01=Site 001 Milton

[BANK234]
BANKNAME=  University Health Network  Toronto Western Hospital
00=Site 001 Toronto Western Hospital

[BANK235]
BANKNAME=Education George Brown College
00=St James Campus  Security
01=Casa Loma Campus  Security

[BANK236]
BANKNAME=  Scarborough Town Centre
00=Site 001 STC

[BANK237]
BANKNAME=  MaRS Discovery Centre
00=Site 001 661 University Avenue

[BANK238]
BANKNAME=Malton
00=Ascension of Our Lord Secondary School 

[BANK239]
BANKNAME=Charlton Campus
00=St Josephs Health Care
01=St Josephs Health Care

[BANK240]
BANKNAME=  Air Transat 
00=Site 001 Terminal 3
01=Site 001 Terminal 3

[BANK241]
BANKNAME=Business Halton Hills
00=Toronto Premium Outlets
01=Toronto Premium Outlets

[BANK242]
BANKNAME=Royal Botanical Gardens Operations
00=SecurityMain
01=Maintenance
02=Events

[BANK243]
BANKNAME=Attractions Exhibition Place
00=Medieval Times Dinner and Tournament

[BANK244]
BANKNAME=Retail Bramalea
00=Bramalea City Centre  Security
01=Bramalea City Centre  Best Buy

[BANK245]
BANKNAME=DriveIn Theatre Sharon
00=Theatre Operations FRS Ch4

[BANK246]
BANKNAME=  CF TorontoDominion Centre
00=Site 001 TD Centre
01=Site 001 TD Centre

[BANK247]
BANKNAME=  College Park
00=Site 001 Toronto College Park

[BANK248]
BANKNAME=Lakeridge Health  Oshawa General Hospital
00=Lakeridge Health  Oshawa General

[BANK249]
BANKNAME=Healthcare Trillium Health Centre  Queensway Ambulatory Centre
00=Security 

[BANK250]
BANKNAME=Business Aurora
00=Diamond Landscaping 

[BANK251]
BANKNAME=Ajax
00=Town of Ajax

[BANK252]
BANKNAME=  Durham NextGen
00=Site 010 South
01=Site 010 South
02=Site 010 South
03=Site 010 North
04=Site 010 South
05=Site 010 East
06=Site 010 North
07=Site 010 North
08=Site 010 South
09=Site 010 North
10=Site 010 East
11=Site 010 South
12=Site 010 North
13=Site 010 East
14=Site 010 North
15=Site 010 South
16=Site 010 East
17=Site 010 North
18=Site 010 East
19=Site 010 East
20=Site 010 East

[BANK253]
BANKNAME=  Toronto Emergency Services
00=Site 005 South
01=Site 005 South
02=Site 007 North
03=Site 007 North
04=Site 006 East
05=Site 005 South
06=Site 008 West
07=Site 006 East
08=Site 008 West
09=Site 005 South
10=Site 007 North
11=Site 006 East
12=Site 007 North
13=Site 008 West
14=Site 005 South
15=Site 006 East
16=Site 005 South
17=Site 007 North
18=Site 006 East
19=Site 008 West
20=Site 005 South
21=Site 005 South
22=Site 007 North
23=Site 006 East
24=Site 008 West
25=Site 005 South
26=Site 007 North
27=Site 006 East
28=Site 008 West
29=Site 005 South
30=Site 007 North
31=Site 008 West
32=Site 005 South
33=Site 005 South
34=Site 007 North
35=Site 008 West
36=Site 007 North
37=Site 005 South
38=Site 005 South
39=Site 006 East
40=Site 008 West
41=Site 007 North
42=Site 005 South
43=Site 005 South
44=Site 007 North
45=Site 006 East
46=Site 008 West
47=Site 005 South
48=Site 007 North
49=Site 005 South
50=Site 008 West
51=Site 007 North
52=Site 005 South
53=Site 008 West
54=Site 007 North
55=Site 005 South
56=Site 009 Rapid Transit 
57=Site 009 Rapid Transit 
58=Site 009 Rapid Transit 
59=Site 009 Rapid Transit 
60=Site 009 Rapid Transit 
61=Site 009 Rapid Transit 
62=Site 009 Rapid Transit 
63=Site 009 Rapid Transit 
64=Site 009 Rapid Transit 

[BANK254]
BANKNAME=  York Region 
00=Site 001 Site 1
01=Site 001 Site 1
02=Site 001 Site 1
03=Site 001 Site 1
04=Site 001 Site 1
05=Site 001 Site 1
06=Site 001 Site 1
07=Site 001 Site 1
08=Site 001 Site 1
09=Site 001 Site 1
10=Site 001 Site 1

[BANK255]
BANKNAME=  Air Canada 
00=Site 001 Primary
01=Site 001 Primary
02=Site 001 Primary
03=Site 001 Primary
04=Site 001 Primary
05=Site 001 Primary
06=Site 001 Primary
07=Site 001 Primary
08=Site 001 Primary
09=Site 001 Primary
10=Site 001 Primary
11=Site 001 Primary
12=Site 001 Primary
13=Site 001 Primary
14=Site 001 Primary

[BANK256]
BANKNAME=  Greater Toronto Airports Authority
00=Site 001 GTAA
01=Site 001 GTAA
02=Site 001 GTAA
03=Site 001 GTAA
04=Site 001 GTAA
05=Site 001 GTAA
06=Site 001 GTAA
07=Site 001 GTAA
08=Site 001 GTAA
09=Site 001 GTAA
10=Site 001 GTAA
11=Site 001 GTAA

[BANK257]
BANKNAME=  US Steel Canada  Stelco 
00=Site 001 Site1
01=Site 001 Site1
02=Site 001 Site1
03=Site 001 Site1
04=Site 001 Site1
05=Site 001 Site1
06=Site 001 Site1

[BANK258]
BANKNAME=  Halton Region 
00=Site 002 North
01=Site 001 South
02=Site 002 North
03=Site 002 North
04=Site 001 South
05=Site 002 North
06=Site 001 South
07=Site 002 North
08=Site 001 South
09=Site 002 North
10=Site 001 South
11=Site 001 South
12=Site 002 North
13=Site 001 South
14=Site 001 South
15=Site 001 South
16=Site 002 North
17=Site 002 North

[BANK259]
BANKNAME=  Hamilton 
00=Site 001 Hamilton
01=Site 001 Hamilton
02=Site 001 Hamilton
03=Site 001 Hamilton
04=Site 001 Hamilton
05=Site 001 Hamilton
06=Site 001 Hamilton
07=Site 001 Hamilton
08=Site 001 Hamilton
09=Site 001 Hamilton
10=Site 001 Hamilton
11=Site 001 Hamilton

[BANK260]
BANKNAME=  Peel Region 
00=Site 001 Peel Region
01=Site 001 Peel Region
02=Site 001 Peel Region
03=Site 001 Peel Region
04=Site 001 Peel Region
05=Site 001 Peel Region
06=Site 001 Peel Region
07=Site 001 Peel Region
08=Site 001 Peel Region
09=Site 001 Peel Region
10=Site 001 Peel Region
11=Site 001 Peel Region
12=Site 001 Peel Region
13=Site 001 Peel Region
14=Site 001 Peel Region
15=Site 001 Peel Region
16=Site 001 Peel Region
17=Site 001 Peel Region
18=Site 001 Peel Region
19=Site 001 Peel Region
20=Site 001 Peel Region

[BANK261]
BANKNAME=Fire Services  Back Up
00=North Command
01=East Command
02=West Command
03=South Command
04=Citywide

[BANK262]
BANKNAME=Fire Services  South Command
00=South Fireground 1 
01=South Fireground 2
02=South Fireground 3
03=South Fireground 4
04=South Fireground 5
05=South Fireground 6 

[BANK263]
BANKNAME=Fire Services  NorthEastWest Command
00=North East West Fireground 1
01=North East West Fireground 2
02=North East West Fireground 3
03=North East West Fireground 4
04=North East West Fireground 5
05=North East West Fireground 6

[BANK264]
BANKNAME=  Maple Leaf Sports and Entertainment
00=Site 001 Air Canada Centre
01=Site 001 Air Canada Centre
02=Site 001 Air Canada Centre
03=Site 001 Air Canada Centre
04=Site 001 Air Canada Centre

[BANK265]
BANKNAME=  Toronto Hydro and Works
00=Site 001 Toronto
01=Site 001 Toronto
02=Site 001 Toronto
03=Site 001 Toronto
04=Site 001 Toronto

[BANK266]
BANKNAME=  Toronto City Services
00=Site 001 Toronto City Services
01=Site 001 Toronto City Services
02=Site 001 Toronto City Services
03=Site 001 Toronto City Services
04=Site 001 Toronto City Services
05=Site 001 Toronto City Services

[BANK267]
BANKNAME=  Fleetcom
00=Site 001 500 Duplex Ave
01=Site 001 500 Duplex Ave
02=Site 001 500 Duplex Ave
03=Site 001 500 Duplex Ave
04=Site 001 500 Duplex Ave
05=Site 001 500 Duplex Ave
06=Site 001 500 Duplex Ave
07=Site 001 500 Duplex Ave

[BANK268]
BANKNAME=  Mobile Business  Toronto LTR  A
00=Site 001 CN Tower
01=Site 001 CN Tower
02=Site 001 CN Tower
03=Site 001 CN Tower
04=Site 001 CN Tower
05=Site 001 CN Tower
06=Site 001 CN Tower
07=Site 001 CN Tower
08=Site 001 CN Tower
09=Site 001 CN Tower
10=Site 001 CN Tower

[BANK269]
BANKNAME=Healthcare Humber River Hospital  Wilson Site
00=Security
01=Security

[BANK270]
BANKNAME=  Brampton City Services
00=Site 001 Brampton
01=Site 001 Brampton
02=Site 001 Brampton
03=Site 001 Brampton
04=Site 001 Brampton
05=Site 001 Brampton
06=Site 001 Brampton

[BANK271]
BANKNAME=  Brampton
00=Site 002 Site 2
01=Site 001 Site 1
02=Site 001 Site 1
03=Site 002 Site 2
04=Site 001 Site 1

[BANK272]
BANKNAME=  Airtime Communications
00=Site 017 Site17
01=Site 017 Site17
02=Site 017 Site17
03=Site 017 Site17
04=Site 017 Site17

[BANK273]
BANKNAME=  Oakville City Services
00=Site 001 BronteRebecca
01=Site 001 BronteRebecca
02=Site 001 BronteRebecca
03=Site 001 BronteRebecca
04=Site 001 BronteRebecca
05=Site 001 BronteRebecca
06=Site 001 BronteRebecca
07=Site 004 Rattlesnake Point
08=Site 004 Rattlesnake Point
09=Site 002 White Oaks  Sector 1
10=Site 002 White Oaks  Sector 1
11=Site 002 White Oaks  Sector 1
12=Site 002 White Oaks  Sector 1
13=Site 002 White Oaks  Sector 1
14=Site 003 White Oaks  Sector 2
15=Site 003 White Oaks  Sector 2
16=Site 003 White Oaks  Sector 2
17=Site 003 White Oaks  Sector 2
18=Site 003 White Oaks  Sector 2
19=Site 003 White Oaks  Sector 2
20=Site 004 Rattlesnake Point

[BANK274]
BANKNAME=  OakvilleTrafalgar Memorial Hospital
00=Site 001 OTMH
01=Site 001 OTMH

[BANK275]
BANKNAME=  General Motors Canada
00=Site 073 Oshawa Car Assembly
01=Site 073 Oshawa Car Assembly
02=Site 073 Oshawa Car Assembly
03=Site 073 Oshawa Car Assembly
04=Site 073 Oshawa Car Assembly
05=Site 073 Oshawa Car Assembly
06=Site 073 Oshawa Car Assembly
07=Site 073 Oshawa Car Assembly
08=Site 073 Oshawa Car Assembly
09=Site 073 Oshawa Car Assembly

[BANK276]
BANKNAME=  Mobile Business  Hamilton 900 MHz
00=Site 002 Unconfirmed LCN
01=Site 001 Confirmed LCN
02=Site 002 Unconfirmed LCN

[BANK277]
BANKNAME=23 cm Band
00=VE3YYZAD   DSTAR
01=VA3GTU  Toronto
02=VE3VGA  Toronto
03=VE3YYZA   DSTAR

