[REV]
ID=1.0.0
APP=IC-PCR1000  Revision 2.2
SOURCE=/home/mainmeister/Projects/RadioReference2PCR1000/metro_22.csv

[BANK00]
BANKNAME=Clarington
00=Darlington Provincial Park Interpark,Multi-Talk,46.760000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Darlington Provincial Park Operations,Multi-Dispatch,46.940000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Darlington Provincial Park,Multi-Talk,149.170000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Clarington Fire Services  Paging,Fire Dispatch,153.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK01]
BANKNAME=Georgina Township
00=Sibbald Point Provincial Park  OMNR CH09,Multi-Dispatch,46.760000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK02]
BANKNAME=Hydro One
00=Hydro One,Utilities,48.910000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Hydro One,Utilities,49.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK03]
BANKNAME=Dundas
00=Spare Work Channel,Utilities,49.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Dispatch,Utilities,49.070000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK04]
BANKNAME=6 M Band
00=VE3SIX  Uxbridge,Ham,53.030000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=VA3PTX  Pefferlaw,Ham,53.090000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=VE3WIK  Carlisle,Ham,53.110000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=VA3PWR  Ballantrae,Ham,53.130000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=VE3PRC  Brampton,Ham,53.190000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=VE3MIS  Mississauga,Ham,53.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=VA3GTU  Toronto,Ham,53.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=VA3ECT  Toronto,Ham,53.390000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=VE3BUO  Burlington ,Ham,53.590000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK05]
BANKNAME=Attractions Canadian Tire Motorsport Park
00=CTMP FM Broadcast,Business,90.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=CTMP Ch 1 TowerKarting Track Operations,Business,151.070000,FM,15k,OFF,250KHz,OFF,OFF,115
02=Bobs Towing wCTMP,Business,163.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Speed TV crews,Business,450.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Speed TV crews,Business,450.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Pratt  Miller Engineering and Fabrication,Business,452.025000,FM,15k,OFF,250KHz,OFF,OFF,306
06=CTMP Control,Business,452.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=NASCAR Ch 1 Safety,Business,452.262500,FM,15k,OFF,250KHz,OFF,OFF,445
08=Bridgestone Racing Academy,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=CTMP Driver Development Track,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,546
10=CTMP Ch 5,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,074
11=CTMP MedicalSecurity,Business,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=CTMP OperationsSafety,Business,461.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=CTMP OpsSafety OldBackup,Business,465.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=CTMP MedicalSecurity OldBackup,Business,465.925000,FM,15k,OFF,250KHz,OFF,OFF,143
15=Flying Lizard Motorsport,Business,465.962500,FM,15k,OFF,250KHz,OFF,OFF,243
16=Star Mazda Series Racing Ch 2,Business,467.012500,FM,15k,OFF,250KHz,OFF,OFF,032
17=Star Mazda Series Racing Ch 1,Business,467.587500,FM,15k,OFF,250KHz,OFF,OFF,032
18=Flying Lizard Motorsport,Business,467.962500,FM,15k,OFF,250KHz,OFF,OFF,664
19=CBS Sports Feed,Media,468.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK06]
BANKNAME=Billy Bishop Toronto City Airport YTZ Air Traffic Control
00=Toronto Island Localizer Runways 08  26,Aircraft,110.150000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Tower,Aircraft,118.200000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Tower alternate,Aircraft,119.200000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Ground,Aircraft,121.700000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=ATIS,Aircraft,133.600000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK07]
BANKNAME=Buttonville Airport YKZ Air Traffic Control
00=ILS  Distance MeasuringLocalizer,Aircraft,111.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Tower alternate,Aircraft,119.900000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Ground,Aircraft,121.800000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Toronto Radio,Aircraft,123.150000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=Tower,Aircraft,124.800000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=Toronto Radio Enroute,Aircraft,126.700000,AM,3k,OFF,25KHz,OFF,OFF,OFF
06=Buttonville ATIS,Aircraft,127.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK08]
BANKNAME=Oshawa Airport YOO CYOO Oshawa Airport
00=Oshawa DMELOC Decommissioned June 2015,Deprecated,111.350000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Oshawa Ground,Aircraft,118.400000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Oshawa Tower,Aircraft,120.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Oshawa ATIS,Aircraft,125.675000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK09]
BANKNAME=Canadian International Air Show CNE Waterfront
00=Snowbirds,Aircraft,116.000000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Show Radar,Aircraft,118.000000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Boss Control,Aircraft,119.200000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Snowbirds,Aircraft,246.500000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=Tiger Ops,Aircraft,268.000000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=Snowbirds,Aircraft,272.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF
06=Hornets,Aircraft,333.300000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK10]
BANKNAME=Toronto Pearson International Airport YYZ Air Traffic Control
00=Tower Backup,Aircraft,118.000000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Tower South,Aircraft,118.350000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Tower North,Aircraft,118.700000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Ground Center,Aircraft,119.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=ATIS Primary,Aircraft,120.825000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=Clearance Delivery,Aircraft,121.300000,AM,3k,OFF,25KHz,OFF,OFF,OFF
06=Ground North,Aircraft,121.650000,AM,3k,OFF,25KHz,OFF,OFF,OFF
07=Ground South,Aircraft,121.900000,AM,3k,OFF,25KHz,OFF,OFF,OFF
08=ATIS Secondary,Aircraft,133.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK11]
BANKNAME=John C Munro International Airport YHM Air Traffic Control
00=Ground,Aircraft,121.600000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Tower  Primary,Aircraft,125.000000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=ATIS,Aircraft,128.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK12]
BANKNAME=Toronto Pearson International Airport YYZ Apron Control
00=South Apron  Terminal 1  East Satellite Ramp  GTAA Hangar  Avitat Ramps,Aircraft,122.075000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=North Apron  Terminal 3  T3 Satellite   Cargo West  Fedex,Aircraft,122.275000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Backup,Aircraft,122.825000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Apron CoOrdinator,Aircraft,122.875000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK13]
BANKNAME=Buttonville Airport YKZ Aviation Business Frequencies
00=Seneca College Flight School Hangars 678,Aircraft,122.225000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=National Helicopters   Hangar 11A,Aircraft,123.200000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK14]
BANKNAME=John C Munro International Airport YHM Airport Services
00=Hamilton Jetport Ltd,Aircraft,122.350000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Shell  Glanford Aviation Services,Aircraft,130.500000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Esso  Hanger 3,Aircraft,131.575000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK15]
BANKNAME=Greenbank Airfield CNP8  Air Traffic Control 
00=ATFUNICOM 5NM4000ASL,Aircraft,122.725000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK16]
BANKNAME=Baldwin Airport CBP9 Air Traffic Control
00=Unicom,Aircraft,122.800000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK17]
BANKNAME=Toronto Pearson International Airport YYZ Private Aviation  Business
00=Landmark Aviation,Aircraft,122.950000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Private Jet Charter Service,Aircraft,129.750000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK18]
BANKNAME=John C Munro International Airport YHM General Aviation
00=Peninsulair Flight School,Aircraft,122.950000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Hamilton Flying Club,Aircraft,123.000000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK19]
BANKNAME=Downsview Airport YZD Air Traffic Control 
00=Automated Weather,Aircraft,122.975000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Unicom  Tower,Aircraft,126.200000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK20]
BANKNAME=Billy Bishop Toronto City Airport YTZ Operations
00=ESSO Aviation,Aircraft,123.200000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Porter  Fixed Base Operations ,Aircraft,123.350000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Toronto Port Authority  City Airport  Runway Snow Clearing ,Aircraft,460.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Toronto Port Authority  City Airport  Maintenance,Business,461.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK21]
BANKNAME=Toronto Pearson International Airport YYZ Airport Services
00=FSS  London Flight Information Centre RCO,Aircraft,123.275000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Field Aviation East,Business,123.500000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=SkyserviceEsso Avitat,Business,128.950000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Central DeIcing Facility  Pads 4 5 6,AM,129.625000,FM,15k,OFF,250KHz,OFF,OFF,5
04=Central DeIcing Facility,Aircraft,131.175000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=Central DeIcing Facility  Pads 1 2 3,AM,131.375000,FM,15k,OFF,250KHz,OFF,OFF,2
06=Central DeIcing Facility Back up,Aircraft,131.950000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK22]
BANKNAME=BramptonCaledon Airport CNC3 Caledon
00=Brampton Flying Club,Aircraft,123.300000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK23]
BANKNAME=Buttonville Airport YKZ Support Services
00=Toronto Airways,Aircraft,123.500000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK24]
BANKNAME=Burlington Airpark  ZBA Air Traffic Control
00=Spectrum Airways,Aircraft,123.500000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK25]
BANKNAME=Toronto Pearson International Airport YYZ Airlines
00=WestJet,Business,123.575000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Air Canada Jazz,Business,129.050000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=American Airlines,Business,129.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Air Georgian,Business,129.150000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=ARINC,Business,129.400000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=Air Canada Jazz Maintenance,Business,129.550000,AM,3k,OFF,25KHz,OFF,OFF,OFF
06=Air Canada Flight Dispatch,Business,129.875000,AM,3k,OFF,25KHz,OFF,OFF,OFF
07=Air Canada International Flights,Business,130.150000,AM,3k,OFF,25KHz,OFF,OFF,OFF
08=Air Canada Jazz Maintenance,Business,130.275000,AM,3k,OFF,25KHz,OFF,OFF,OFF
09=Air Canada Domestic Flights,Business,130.375000,AM,3k,OFF,25KHz,OFF,OFF,OFF
10=Delta Airlines,Business,130.475000,AM,3k,OFF,25KHz,OFF,OFF,OFF
11=Swissport,Business,130.650000,AM,3k,OFF,25KHz,OFF,OFF,OFF
12=Air Canada Station Operations Centre,Business,130.875000,AM,3k,OFF,25KHz,OFF,OFF,OFF
13=US Airways,Business,131.650000,AM,3k,OFF,25KHz,OFF,OFF,OFF
14=Air Transat,Business,131.875000,AM,3k,OFF,25KHz,OFF,OFF,OFF
15=Airport Terminal Services,Business,136.575000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK26]
BANKNAME=Toronto Pearson International Airport YYZ Toronto Centre  Terminal Control Unit
00=Arrivals 2,Aircraft,124.475000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Arrivals 3,Aircraft,125.400000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=North Departure,Aircraft,127.575000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=South Departure,Aircraft,128.800000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=Arrivals 1,Aircraft,132.800000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=ILS Monitor ,Aircraft,134.175000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK27]
BANKNAME=Billy Bishop Toronto City Airport YTZ CYTZ
00=Air Canada Rapidair,Aircraft,128.875000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Porter Airlines,Aircraft,128.975000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Porter Airlines,Aircraft,131.050000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Porter Airlines,Aircraft,136.875000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK28]
BANKNAME=John C Munro International Airport YHM Cargo Carriers
00=Purolator Courier Ltd,Aircraft,128.950000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=United Parcel Service Canada,Business,129.425000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Cargo Jet Canada Ltd,Aircraft,130.675000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=Federal Express Canada,Aircraft,131.925000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK29]
BANKNAME=Oshawa Airport YOO Flight School
00=Canadian Flight Academy,Aircraft,129.100000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK30]
BANKNAME=Toronto Pearson International Airport YYZ ACARS
00=ARINC Toronto,Data,129.125000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=ARINC Toronto,Data,130.025000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=ARINC Toronto,Data,131.475000,AM,3k,OFF,25KHz,OFF,OFF,OFF
03=ARINC Toronto,Data,131.550000,AM,3k,OFF,25KHz,OFF,OFF,OFF
04=SITACOM Canada,Data,131.725000,AM,3k,OFF,25KHz,OFF,OFF,OFF
05=ARINC Toronto  VDL Mode 2,Data,136.975000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK31]
BANKNAME=Downsview Airport YZD Bombardier Aerospace
00=Tower,Aircraft,130.075000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=Plant Operations,Business,454.200000,FM,15k,OFF,250KHz,OFF,OFF,627

[BANK32]
BANKNAME=Oshawa Airport YOO Fuel Operations
00=Enterprise Air,Aircraft,131.050000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK33]
BANKNAME=John C Munro International Airport YHM Airlines
00=CanJet,Aircraft,131.075000,AM,3k,OFF,25KHz,OFF,OFF,OFF
01=WestJet,Aircraft,131.675000,AM,3k,OFF,25KHz,OFF,OFF,OFF
02=Westjet  Ops,Aircraft,408.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Air Transat Operations,Aircraft,458.662500,FM,15k,OFF,250KHz,OFF,OFF,023

[BANK34]
BANKNAME=Toronto Pearson International Airport YYZ Cargo Carriers
00=Federal Express,Aircraft,131.925000,AM,3k,OFF,25KHz,OFF,OFF,OFF

[BANK35]
BANKNAME=Business Georgetown
00=First Student Canada,Transportation,140.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK36]
BANKNAME=Business Burlington
00=First Student Canada,Transportation,140.280000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Dufferin Concrete  ,Business,164.790000,FM,15k,OFF,250KHz,OFF,OFF,143
02=Canadian Building Materials ,Business,171.930000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Burlington Taxi,Transportation,407.387500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Contro Valve,Business,408.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Burlington Mall  Security,Security,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Attridge Transportation ,Transportation,452.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Mapleview Centre  Security,Security,453.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Attridge Transportation ,Transportation,460.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Homestead LandHoldings  Maintenance,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK37]
BANKNAME=Business Markham
00=First Canada ULC,Schools,140.340000,FM,15k,OFF,250KHz,OFF,OFF,255
01=Markham Taxi,Transportation,165.870000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Markville Shopping Centre  Security ,Security,462.825000,FM,15k,OFF,250KHz,OFF,OFF,251
03=Markville Shopping Centre  Property Management,Business,463.850000,FM,15k,OFF,250KHz,OFF,OFF,251

[BANK38]
BANKNAME=Business King City
00=Sharp Bus Lines Ch 1,Transportation,140.910000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Sharp Bus Lines Ch 2,Transportation,150.965000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=A Cab Taxi Services,Transportation,154.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=First Student Canada,Schools,165.315000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Stock Transportation,Transportation,165.630000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK39]
BANKNAME=Transportation Caledon East
00=First Student Canada,Transportation,141.030000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=First Student Canada,Transportation,148.030000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK40]
BANKNAME=Business Oakville
00=First Student Canada,Transportation,141.150000,FM,15k,OFF,250KHz,OFF,OFF,412
01=Halton Taxi,Transportation,166.380000,FM,15k,OFF,250KHz,OFF,OFF,412
02=Stock Transportation,Transportation,168.045000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=BOT Construction ,Business,172.590000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=BOT Construction ,Business,172.980000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Oakville Place  Security  ,Security,451.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Hopedale Mall  Security ,Security,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Trafalgar Heights  Property Management,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=United Taxi,Transportation,458.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Holiday Inn Select ,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=5 Drive In Theatre,Business,463.850000,FM,15k,OFF,250KHz,OFF,OFF,371
11=Home Depot  2555 Bristol Circle,Business,464.262500,FM,15k,OFF,250KHz,OFF,OFF,065

[BANK41]
BANKNAME=Transportation Brampton
00=Stock Transportation,Transportation,141.150000,FM,15k,OFF,250KHz,OFF,OFF,412
01=Switzer Carty,Transportation,155.550000,FM,15k,OFF,250KHz,OFF,OFF,265
02=Parkinson Coach Lines ,Transportation,158.505000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Stock Transportation,Transportation,165.360000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Kwik Cab ,Transportation,168.210000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Bram City Taxi,Transportation,168.810000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Attridge Transportation,Transportation,452.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=A Seven Eleven Taxi ,Transportation,453.862500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Airline Limo,Transportation,458.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK42]
BANKNAME=  Bell FleetNet  Ontario Provincial Government Zone 1
00=Site 039 King City 39KING,TRS,141.195000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 040 Mowat 40MOWT Toronto,TRS,141.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 005 Ballinafad 05BALL,TRS,141.360000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 037 Whitby 37WHIT,TRS,141.390000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 007 Charlton 07CHAR Hamilton,TRS,141.405000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 009 Britannia 09BRIT Mississauga,TRS,141.420000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 040 Mowat 40MOWT Toronto,TRS,141.435000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 026 Sunderland 26SUND,TRS,141.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 038 Pontypool 38PONT,TRS,141.495000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 005 Ballinafad 05BALL,TRS,141.540000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 007 Charlton 07CHAR Hamilton,TRS,141.630000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 039 King City 39KING,TRS,141.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 038 Pontypool 38PONT,TRS,141.705000,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 026 Sunderland 26SUND,TRS,141.720000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 005 Ballinafad 05BALL,TRS,141.735000,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 007 Charlton 07CHAR Hamilton,TRS,141.930000,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 037 Whitby 37WHIT,TRS,142.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 040 Mowat 40MOWT Toronto,TRS,142.110000,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 039 King City 39KING,TRS,142.140000,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 009 Britannia 09BRIT Mississauga,TRS,142.185000,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 007 Charlton 07CHAR Hamilton,TRS,142.215000,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=Site 005 Ballinafad 05BALL,TRS,142.245000,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=Site 037 Whitby 37WHIT,TRS,142.290000,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=Site 026 Sunderland 26SUND,TRS,142.320000,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=Site 037 Whitby 37WHIT,TRS,142.335000,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=Site 007 Charlton 07CHAR Hamilton,TRS,142.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=Site 009 Britannia 09BRIT Mississauga,TRS,142.365000,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=Site 039 King City 39KING,TRS,142.380000,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=Site 037 Whitby 37WHIT,TRS,142.425000,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=Site 005 Ballinafad 05BALL,TRS,142.455000,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=Site 038 Pontypool 38PONT,TRS,142.590000,FM,15k,OFF,250KHz,OFF,OFF,OFF
31=Site 005 Ballinafad 05BALL,TRS,142.605000,FM,15k,OFF,250KHz,OFF,OFF,OFF
32=Site 007 Charlton 07CHAR Hamilton,TRS,142.635000,FM,15k,OFF,250KHz,OFF,OFF,OFF
33=Site 026 Sunderland 26SUND,TRS,142.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF
34=Site 009 Britannia 09BRIT Mississauga,TRS,142.665000,FM,15k,OFF,250KHz,OFF,OFF,OFF
35=Site 040 Mowat 40MOWT Toronto,TRS,142.680000,FM,15k,OFF,250KHz,OFF,OFF,OFF
36=Site 009 Britannia 09BRIT Mississauga,TRS,142.755000,FM,15k,OFF,250KHz,OFF,OFF,OFF
37=Site 039 King City 39KING,TRS,142.785000,FM,15k,OFF,250KHz,OFF,OFF,OFF
38=Site 007 Charlton 07CHAR Hamilton,TRS,142.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF
39=Site 037 Whitby 37WHIT,TRS,142.830000,FM,15k,OFF,250KHz,OFF,OFF,OFF
40=Site 026 Sunderland 26SUND,TRS,142.860000,FM,15k,OFF,250KHz,OFF,OFF,OFF
41=Site 038 Pontypool 38PONT,TRS,142.890000,FM,15k,OFF,250KHz,OFF,OFF,OFF
42=Site 040 Mowat 40MOWT Toronto,TRS,142.905000,FM,15k,OFF,250KHz,OFF,OFF,OFF
43=Site 039 King City 39KING,TRS,142.920000,FM,15k,OFF,250KHz,OFF,OFF,OFF
44=Site 039 King City 39KING,TRS,142.980000,FM,15k,OFF,250KHz,OFF,OFF,OFF
45=Site 009 Britannia 09BRIT Mississauga,TRS,142.995000,FM,15k,OFF,250KHz,OFF,OFF,OFF
46=Site 038 Pontypool 38PONT,TRS,143.055000,FM,15k,OFF,250KHz,OFF,OFF,OFF
47=Site 009 Britannia 09BRIT Mississauga,TRS,143.070000,FM,15k,OFF,250KHz,OFF,OFF,OFF
48=Site 007 Charlton 07CHAR Hamilton,TRS,143.085000,FM,15k,OFF,250KHz,OFF,OFF,OFF
49=Site 026 Sunderland 26SUND,TRS,143.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
50=Site 037 Whitby 37WHIT,TRS,143.145000,FM,15k,OFF,250KHz,OFF,OFF,OFF
51=Site 038 Pontypool 38PONT,TRS,143.265000,FM,15k,OFF,250KHz,OFF,OFF,OFF
52=Site 026 Sunderland 26SUND,TRS,143.280000,FM,15k,OFF,250KHz,OFF,OFF,OFF
53=Site 005 Ballinafad 05BALL,TRS,143.295000,FM,15k,OFF,250KHz,OFF,OFF,OFF
54=Site 009 Britannia 09BRIT Mississauga,TRS,143.310000,FM,15k,OFF,250KHz,OFF,OFF,OFF
55=Site 005 Ballinafad 05BALL,TRS,143.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
56=Site 040 Mowat 40MOWT Toronto,TRS,143.340000,FM,15k,OFF,250KHz,OFF,OFF,OFF
57=Site 039 King City 39KING,TRS,143.355000,FM,15k,OFF,250KHz,OFF,OFF,OFF
58=Site 039 King City 39KING,TRS,143.370000,FM,15k,OFF,250KHz,OFF,OFF,OFF
59=Site 007 Charlton 07CHAR Hamilton,TRS,143.385000,FM,15k,OFF,250KHz,OFF,OFF,OFF
60=Site 009 Britannia 09BRIT Mississauga,TRS,143.505000,FM,15k,OFF,250KHz,OFF,OFF,OFF
61=Site 040 Mowat 40MOWT Toronto,TRS,143.640000,FM,15k,OFF,250KHz,OFF,OFF,OFF
62=Site 009 Britannia 09BRIT Mississauga,TRS,143.730000,FM,15k,OFF,250KHz,OFF,OFF,OFF
63=Site 039 King City 39KING,TRS,143.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
64=Site 040 Mowat 40MOWT Toronto,TRS,152.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK43]
BANKNAME=Transportation Mississauga
00=First Student Canada ,Transportation,141.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=The Cab Company,Transportation,150.845000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=A Black Cab,Transportation,150.845000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Trott Transit,Transportation,158.610000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Switzer Carty  Long Bus ,Transportation,158.610000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=A Black Cab,Transportation,164.850000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Switzer Carty  Short BusVans ,Transportation,166.560000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=First Student Canada ,Transportation,167.985000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=First Student Canada ,Transportation,171.465000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Golden Taxi,Transportation,412.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Blue  White Taxi,Transportation,452.612500,FM,15k,OFF,250KHz,OFF,OFF,245
11=Attridge Transportation,Transportation,460.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Attridge Transportation,Transportation,462.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=All Star Taxi,Transportation,464.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK44]
BANKNAME=2 M Band
00=VE3YYZ DSTAR  Toronto,Ham,144.940000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=VE3WOO  Toronto,Ham,145.110000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=VA3GTU  Toronto,Ham,145.130000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=VE3OBN  Toronto,Ham,145.230000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=VE3GSR  King City,Ham,145.310000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=VE3YRA  King City,Ham,145.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=VE3CTV  Toronto,Ham,145.370000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=VE3TWR  Toronto,Ham,145.410000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=VE3MIS  Mississauga,Ham,145.430000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=VE3PYL  Mississauga,Ham,145.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=VE3ULR  Ballantrae,Ham,145.470000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=VE3WAS  King City,Ham,146.610000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=VE3RDP  Inglewood,Ham,146.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=VE3WIK  Carlisle,Ham,146.715000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=VA3RTC  Toronto,Ham,146.745000,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=VE3NCF  Hamilton,Ham,146.760000,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=VE3PRC Brampton,Ham,146.880000,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=VE3RAE Burlington ARES Backup,Ham,146.895000,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=VE3TOR  Toronto,Ham,146.940000,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=VA3SUP  Whitby,Ham,146.970000,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=VE3SKY  Toronto,Ham,146.985000,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=VE3OAK  Oakville,Ham,147.015000,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=VE3RSS  Acton,Ham,147.030000,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=VE3RPT  Uxbridge,Ham,147.060000,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=VE3OSH  Oshawa,Ham,147.120000,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=VE3OD  Georgetown  Halton ARES,Ham,147.135000,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=VE3WOM  Whitby,Ham,147.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=VE3YRK DSTAR,Ham,147.180000,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=VE3MOT  Richmond Hill,Ham,147.180000,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=VE3RSB  Burlington ARES,Ham,147.210000,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=VE3YRC  Aurora,Ham,147.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
31=VE3TNC  Toronto,Ham,147.270000,FM,15k,OFF,250KHz,OFF,OFF,OFF
32=VA3BAL  Ballantrae,Ham,147.330000,FM,15k,OFF,250KHz,OFF,OFF,OFF
33=VE3PDX  Stoney Creek,Ham,147.345000,FM,15k,OFF,250KHz,OFF,OFF,OFF
34=VE3SPA  Pickering,Ham,147.375000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK45]
BANKNAME=Business Vaughan
00=Maloron Communications ,Business,148.195000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Astro Taxi COOP,Transportation,163.080000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Vaughan Mills  Security ,Security,452.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=United Parcel Service  Trailers,Business,452.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=United Parcel Service  Hub Control,Business,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Vaughan Mills  Property Management,Business,462.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK46]
BANKNAME=Business School Buses
00=Cardinal ,Transportation,148.435000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Stock Transportation,Transportation,157.545000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Stock Transportation,Transportation,158.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Cardinal ,Transportation,162.060000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=First Student Canada,Schools,164.190000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Maloron Communications Leased  Dispatch,Transportation,166.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Maloron Communications Leased  Dispatch,Transportation,166.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Stock Transportation,Transportation,170.310000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=First Student Canada,Schools,171.180000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=First Student Canada,Schools,172.080000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=McCluskey,Transportation,453.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK47]
BANKNAME=Business Taxi
00=OnTime taxi,Transportation,148.555000,FM,15k,OFF,250KHz,OFF,OFF,155
01=Crown Taxi,Transportation,150.215000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Beck Taxi subcontract for WheelTrans Cars,Transportation,150.280000,FM,15k,OFF,250KHz,OFF,OFF,223
03=Able Atlantic Taxi,Transportation,150.310000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Able Atlantic Taxi,Transportation,150.485000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Metro Cab,Transportation,150.815000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Beck Taxi subcontract for WheelTrans Dispatch,Transportation,154.845000,FM,15k,OFF,250KHz,OFF,OFF,223
07=Royal Taxi ,Transportation,154.920000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Beck Taxi subcontract for WheelTrans Cars,Transportation,155.520000,FM,15k,OFF,250KHz,OFF,OFF,223
09=Beck Taxi ,Transportation,159.135000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=AAA Best Choice Taxi,Transportation,159.990000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Beck Taxi,Transportation,162.720000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Beck Taxi subcontract for WheelTrans Cars,Transportation,162.780000,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Crown Taxi,Transportation,163.230000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Beck Taxi,Transportation,163.290000,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Beck Taxi subcontract for WheelTrans Cars,Transportation,163.590000,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Crown Taxi 2 Bloor Street E,Transportation,163.785000,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Beck Taxi  Central Dispatch  ,Transportation,163.875000,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Crown Taxi Inc,Transportation,164.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=AAA Best Choice Taxi,Transportation,164.460000,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=COOP Cabs,Transportation,168.660000,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=5 Star Taxi,Transportation,169.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=Beck Taxi  WheelTrans,Transportation,170.070000,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=Maple Leaf Cabs,Transportation,170.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=City Taxi  Central Dispatch,Transportation,170.820000,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=Beck Taxi ,Transportation,171.060000,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=Beck Taxi ,Transportation,171.360000,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=Kingsboro Taxi ,Transportation,171.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=Scarborough Taxi,Transportation,406.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=Scarborough Taxi,Transportation,408.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=ABC Ambassadors Taxi,Transportation,451.387500,FM,15k,OFF,250KHz,OFF,OFF,125
31=Bee Line Taxi,Transportation,458.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK48]
BANKNAME=Education Toronto District School Board
00=Second St Middle,Schools,149.110000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Mowat CI,Schools,451.187500,FM,15k,OFF,250KHz,OFF,OFF,054
02=Rawlinson Community School,Schools,453.450000,FM,15k,OFF,250KHz,OFF,OFF,205
03=Rivercrest Junior School,Schools,453.637500,FM,15k,OFF,250KHz,OFF,OFF,413

[BANK49]
BANKNAME=Ontario Power Generation  Pickering
00=Ontario Power Generation  Paging ,Data,149.290000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK50]
BANKNAME=Business Clarington
00=Bell Mobile Paging,Data,149.770000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Algoma Orchards,Business,151.580000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Dufferin Concrete,Business,152.045000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Student Transportation of Canada,Schools,165.735000,FM,15k,OFF,250KHz,OFF,OFF,423
04=Phoenix Transportation,Schools,166.005000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=First Student Canada,Schools,168.900000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Canada Building Materials,Business,171.930000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Dufferin Concrete,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Bowmanville Taxi,Business,452.512500,FM,15k,OFF,250KHz,OFF,OFF,364
09=Petro Canada,Data,453.450000,FM,15k,OFF,250KHz,OFF,OFF,125
10=Kobes Nurseries,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,251
11=St Marys Cement Plant,Business,460.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Student Transportation Services of Central Ontario,Schools,461.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Williams Communications,Business,463.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=WalMart Canada,Business,464.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Shoppers Drug Mart  Longworth,Business,464.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Covanta Durham York Renewable Energy,Business,464.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Cineplex Odeon,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK51]
BANKNAME=Business Oshawa
00=TaxiTaxi,Transportation,150.070000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Miller Paving,Business,151.085000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Morris Chemicals,Business,151.085000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=City Wide Taxi,Transportation,151.760000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Bobs Towing,Business,163.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Durhamway School Bus,Schools,170.415000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=GenAuto Shippers,Business,172.980000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK52]
BANKNAME=Whitby Hydro Energy Services Corporation
00=Whitby Hydro Energy Services Corporation,Utilities,150.425000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK53]
BANKNAME=Golf Courses Burlington Golf and Country Club
00=Operations,Business,150.455000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK54]
BANKNAME=Regionwide
00=Hamilton EMS  Paging,EMS Dispatch,150.575000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Hamilton EMS  Paging ,EMS Dispatch,150.695000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Fire Dispatch  Regional South,Fire Dispatch,152.345000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Fire Dispatch Trunk Simulcast,Fire Dispatch,154.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Hamilton Regional Conservation Authority,Public Works,162.735000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Region Plows,Public Works,163.170000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Region Plows,Public Works,164.730000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Hamilton Regional Conservation Authority,Public Works,165.345000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Durham Region Works Alarms,Data,168.960000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK55]
BANKNAME=Media Rogers Communications
00=Traffic,Media,150.670000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Darryl Dahmer  Skymaster 1,Media,150.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK56]
BANKNAME=Ontario Community Emergency Assistance Program
00=Ontario Community Emergency Assistance Program,Emergency Ops,151.055000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Ontario Community Emergency Assistance Program,Emergency Ops,151.085000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Ontario Community Emergency Assistance Program,Emergency Ops,151.155000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK57]
BANKNAME=Business Whitby
00=LocPipe,Business,151.055000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Pilgrim Transportation Services,Transportation,152.270000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Dufferin Concrete,Business,158.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Circle Taxi,Transportation,165.030000,FM,15k,OFF,250KHz,OFF,OFF,115
04=Liquor Control Board Ontario  Durham Warehouse Ch 1 ,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Liquor Control Board Ontario  Durham Warehouse Ch 2,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Liquor Control Board Ontario  Durham Warehouse Ch 3,Business,459.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Liquor Control Board Ontario  Durham Warehouse Ch 4,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Atlantic Packaging,Business,462.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK58]
BANKNAME=Bolton
00=Peel Regional Road 50 Weigh Scales ,Public Works,151.070000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK59]
BANKNAME=Business Brock Township
00=Canada Building Materials,Business,151.085000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK60]
BANKNAME=African Lion Safari African Lion Safari
00=Tour Guides  Wardens,Business,151.085000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Channel 2,Business,151.580000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Channel 1  Main,Business,154.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Koho Food Services,Business,155.415000,FM,15k,OFF,250KHz,OFF,OFF,606
04=Safari Outfitters,Business,166.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Operations,Business,166.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK61]
BANKNAME=Hamilton General
00=Cardiac Ward Paging,Hospital,151.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Security,Security,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK62]
BANKNAME=Attractions The Clarington Family Outdoor Adventure Park
00=The Clarington Family Outdoor Adventure Park,Business,151.100000,FM,15k,OFF,250KHz,OFF,OFF,226
01=Bowmanville Zoo ,Business,151.580000,FM,15k,OFF,250KHz,OFF,OFF,226

[BANK63]
BANKNAME=  MetroNET
00=Site 001 MetroNET,TRS,151.295000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK64]
BANKNAME=Business Construction
00=Dufferin Concrete ,Business,151.565000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Dufferin Concrete,Business,154.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Dufferin Concrete ,Business,165.420000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Canadian Building Materials,Business,168.765000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Innocon Concrete  Mississauga Yard ,Business,170.010000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Innocon Concrete  Data,Data,170.580000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Teskey Construction ,Business,171.630000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=CBM Concrete,Business,171.930000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Daniels,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,506
09=Amherst Crane Rental,Business,461.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Stacey Electric ,Business,461.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Metrix Ready Mix,Business,463.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=AECON,Business,463.850000,FM,15k,OFF,250KHz,OFF,OFF,464
13=Daniels,Business,468.962500,FM,15k,OFF,250KHz,OFF,OFF,025

[BANK65]
BANKNAME=Business Waterdown
00=Connon Nurseries Ch 1,Business,151.580000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Connon Nurseries Ch 2,Business,152.015000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Connon Nurseries Ch 3,Business,153.620000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=BrennBFarms  Westover,Business,169.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Attridge Transportation,Transportation,462.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK66]
BANKNAME=Toronto Transit Commission
00=Streetcar Maintenance of Way,Transportation,151.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Security Simplex,Security,406.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Surface Ch1 Transit Control,Transportation,412.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Surface Ch2 WheelTrans,Transportation,412.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Surface Ch3 ,Transportation,412.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=RT Yard,Transportation,412.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Surface Ch 4 ,Transportation,412.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Surface Ch5 Streetcars,Transportation,412.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=RT Line,Transportation,412.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Surface Ch6 SubwaySRT Yard,Transportation,413.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Surface Ch7 Subway Maintenance,Transportation,418.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK67]
BANKNAME=Media Bell Media Queen Street Bureau
00=CTV CP24  Mobile Link,Media,152.090000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=CP24  Wireless,Media,457.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=CP24  Wireless ,Media,457.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=CP24  Wireless ,Media,468.762500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=CP24  Wireless ,Media,470.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=CP24  Wireless ,Media,470.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=CP24  Wireless ,Media,476.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=CP24  Wireless,Media,493.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK68]
BANKNAME=Attractions Live Nation
00=Food and Beverage  Warehouse ,Business,152.240000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Guest Services,Business,154.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Food and Beverage,Business,154.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Food and Beverage  Venue,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK69]
BANKNAME=Business Hamilton
00=Sharp Bus Lines,Transportation,152.525000,FM,15k,OFF,250KHz,OFF,OFF,205
01=Kenneth R Awrey,Business,154.490000,FM,15k,OFF,250KHz,OFF,OFF,412
02=Dufferin Concrete,Business,158.175000,FM,15k,OFF,250KHz,OFF,OFF,411
03=Caledonia Transportation,Transportation,162.165000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Caledonia Transportation,Business,162.165000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Lafarge Paving and Costruction,Business,163.020000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Dufferin Concrete,Business,163.065000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Dufferin Concrete,Business,164.790000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Jackson Square Mall,Business,451.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Jackson Square Mall,Business,451.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Jackson Square Mall,Business,451.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Cineplex  Silvercity Ancaster ,Business,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Limeridge Mall  Security,Security,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Bunge Canada  Maintenance,Business,451.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Caledonia Transportation,Transportation,452.437500,FM,15k,OFF,250KHz,OFF,OFF,662
15=Cardi Construction,Business,453.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Hamilton Cab ,Transportation,454.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Eastgate Square,Business,460.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=ArcelorMittal Dofasco  Fire and EMS,Multi-Dispatch,463.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=The Centre on Barton  Security,Security,463.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=ArcelorMittal Dofasco  Security,Security,463.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=Yellow Cab Company,Transportation,463.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=First Response Environmental,Business,464.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=Empire Jackson Square 6 Theatres,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK70]
BANKNAME=  Horizon Utilities Corporation 
00=Site 001 Hamilton,TRS,152.585000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Hamilton,TRS,153.470000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK71]
BANKNAME=McMaster University
00=Maintenance,Schools,153.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01= Reactor,Other,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK72]
BANKNAME=Hamilton
00=Work Channel,Utilities,153.545000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Horizon Utilities,Utilities,154.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK73]
BANKNAME=Oshawa PUC Networks
00=Oshawa PUC Networks,Utilities,153.590000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Oshawa PUC Networks  Simplex,Utilities,153.740000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK74]
BANKNAME=Richmond Hill
00=Central York Fire Service  Paging,Fire Dispatch,153.665000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Works Operations,Public Works,164.265000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=B1  Fire  Emergency Services  Simplex ,Fire-Tac,851.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=B16   Fire Repeater B,Fire-Tac,852.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK75]
BANKNAME=Townships of Brock Scugog Town of Uxbridge Fire Services
00=North Durham Region Fire  Paging,Fire Dispatch,153.860000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK76]
BANKNAME=  Caledon Town
00=Site 001 Concession 6,TRS,153.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Concession 6,TRS,169.155000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK77]
BANKNAME=Milton
00=Fire Dispatch ,Fire Dispatch,154.160000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Maplehurst Correctional Complex,Corrections,410.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Hydro,Utilities,411.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Vanier Centre For Women Maplehurst,Corrections,411.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Fire Dispatch  UHF link,Fire Dispatch,414.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Kelso Conservation Area,Business,454.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Rattlesnake Point Conservation Area,Business,454.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Halton Region Waste Management,Public Works,462.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK78]
BANKNAME=Halton Hills
00=Town Fire Department,Fire Dispatch,154.160000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Hydro,Utilities,410.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK79]
BANKNAME=Burlington
00=Fire Dispatch  Simulcast,Fire Dispatch,154.205000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Hydro,Utilities,169.290000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=OPP Rebroadcast,Law Dispatch,413.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK80]
BANKNAME=Business Pickering
00=Royal Ashburn Golf Club,Business,154.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Dufferin Concrete,Business,165.420000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Dufferin Ready Mix,Business,166.620000,FM,15k,OFF,250KHz,OFF,OFF,411
03=Student Transportation of Canada,Transportation,171.105000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK81]
BANKNAME=Business Various
00=Town II Condominium  Property Management ,Business,154.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Locus Electric ,Business,451.662500,FM,15k,OFF,250KHz,OFF,OFF,134
02=Toronto Ontario Temple  The Church of Jesus Christ of Latterday Saints,Business,452.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Freemont Landscaping,Business,463.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=TST Overland Express,Business,463.850000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK82]
BANKNAME=Business Newmarket
00=Switzer Carty Bus,Transportation,155.550000,FM,15k,OFF,250KHz,OFF,OFF,265
01=Stock Transportation,Transportation,170.790000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Upper Canada Mall ,Business,452.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Best Buy,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Michaels,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Upper Canada Mall  Security,Security,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Silver City Theatre,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,532
07=York District School Board,Schools,462.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK83]
BANKNAME=City Services
00=Hamilton Port Authority,Federal,155.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Hamilton Port Authority  GPS location data,Data,155.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Hamilton Street Railway Dispatch,Transportation,410.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Hamilton Street Railway  Supervisors,Transportation,411.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Waste Management,Public Works,411.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Hamilton Street Railway,Transportation,411.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Hamilton Street Railway,Transportation,411.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=City Parking Enforcement,Public Works,451.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Police Simplex,Law Tac,868.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=ERU Simplex,Law Tac,868.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Fire  Simplex,Fire-Tac,868.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Works  Traffic  Simplex,Public Works,868.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK84]
BANKNAME=Region Wide
00=Dispatch  MississaugaBrampton and Caledon,Data,156.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Municipal Works Dept,Public Works,164.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=MOH Base Station Paging,EMS Dispatch,414.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=York Region District School Board,Schools,462.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK85]
BANKNAME=Retail Mississauga
00=Lowes  5348 Mavis Road,Business,157.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Dixie Outlet Mall  Security ,Security,454.200000,FM,15k,OFF,250KHz,OFF,OFF,664
02=Dixie Outlet Mall  Maintenance,Business,454.200000,FM,15k,OFF,250KHz,OFF,OFF,664
03=Heartland Town Centre  Michaels,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Winston Argentia Centre  Best Buy,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Square One  Microsoft Store,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Heartland Town Centre  Old Navy,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Erin Mills Town Centre  Old Navy,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Square One  Property Management ,Business,460.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Square One  Security,Security,460.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Meadowvale Town Centre ,Business,462.825000,FM,15k,OFF,250KHz,OFF,OFF,261
11=Heartland Town Centre  Best Buy,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Erin Mills Town Plaza  HomeSense,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,174
13=Costco  3180 Laird Road,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,664
14=Winston Argentia Centre  Bed Bath and Beyond,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=National Sports  2921 Eglinton AveWest,Business,469.292500,FM,15k,OFF,250KHz,OFF,OFF,026

[BANK86]
BANKNAME=Vaughan
00=Vaughan Parks Joint Operations Centre,Public Works,158.790000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Vaughan Works Joint Operations Centre,Public Works,159.405000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=A1  Fire  Rescue   Simplex,Fire-Tac,851.900000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=A16  Fire Repeater A,Fire-Tac,852.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Expertech onsite Joint Operations Centre,Utilities,935.115000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK87]
BANKNAME=Government of Canada
00=Industry Canada,Federal,159.810000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK88]
BANKNAME=Business Couriers
00=Jesk Enterprises Ltd,Business,162.240000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=TransOntario Express,Business,163.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Flying Dutchman,Business,451.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Arrowspeed Delivery,Business,452.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=DKR Courier Service,Business,462.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=United Messengers ,Business,462.387500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Golden Arrow Courier,Business,463.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK89]
BANKNAME=  Talk Wireless LTR VHF Hamilton
00=Site 001 Confirmed LCN,TRS,162.255000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Confirmed LCN,TRS,164.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Confirmed LCN,TRS,166.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK90]
BANKNAME=Business Cranston
00=Caledonia Transportation ,Transportation,162.570000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK91]
BANKNAME=Business Dundas
00=Carmeuse Lime and Stone,Business,162.810000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK92]
BANKNAME=Business Airport Taxi and Limousine
00=Aerofleet Taxi,Transportation,163.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Airflight Service,Transportation,166.710000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Aerofleet Taxi,Transportation,167.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Airline Limousine,Transportation,451.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Aeroport Taxi,Transportation,452.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Aircab,Transportation,461.862500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK93]
BANKNAME=Business Milton
00=Union Gas ,Utilities,163.770000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Oak Concrete ,Business,173.820000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=CoSteel Recycling,Business,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=CoSteel Recycling,Business,458.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Dufferin Aggregates,Business,460.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Dufferin Aggregates,Business,460.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=A Black Cab,Transportation,463.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK94]
BANKNAME=Business Lynden
00=Joost AH Dr Blieck Josnar Acres,Business,163.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK95]
BANKNAME=  Telequip Systems King City
00=Site 001 King City,TRS,163.905000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 King City,TRS,164.580000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 King City,TRS,166.440000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK96]
BANKNAME=Business Bradford
00=Parkview Transit ,Transportation,164.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK97]
BANKNAME=Business Limehouse
00=Fred J Anthony   Agricultural Chemicals,Business,164.355000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK98]
BANKNAME=Business Vinemount
00=Waterford Sand and Gravel,Business,165.585000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK99]
BANKNAME=  Yorkdale Shopping Centre
00=Site 001 Yorkdale,TRS,165.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Yorkdale,TRS,166.620000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK100]
BANKNAME=Attractions North York
00=Ontario Science Centre  Security,Security,165.930000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK101]
BANKNAME=Scugog Township
00=Township Roads Dept ,Public Works,166.890000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK102]
BANKNAME=Business Richmond Hill
00=Stock Transportation,Transportation,167.130000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Advance Unique Taxi,Transportation,172.845000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK103]
BANKNAME=Business Ancaster
00=First Student Canada,Transportation,167.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK104]
BANKNAME=Oakville REACT
00=Special Events,Ham,168.990000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK105]
BANKNAME=Pickering
00=Engineering  Public Works,Public Works,169.290000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK106]
BANKNAME=Aurora
00=Town Works Dept,Public Works,169.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK107]
BANKNAME=Markham
00=Town Works Dept,Public Works,169.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=C1  Fire  Emergency Services  Simplex,Fire-Tac,852.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=C16  Fire Repeater C,Fire-Tac,852.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK108]
BANKNAME=Business Westover
00=BrennBFarms,Business,169.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK109]
BANKNAME=Volunteer Organizations Special Events
00=Respond Search and Rescue,Business,169.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK110]
BANKNAME=Business Ajax
00=Innocon Inc,Business,170.010000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=First Student Canada,Schools,171.480000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK111]
BANKNAME=Business Flamborough
00=Airway Transit Service,Transportation,170.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Airways Transit Services,Transportation,407.912500,FM,15k,OFF,250KHz,OFF,OFF,226

[BANK112]
BANKNAME=Business Uxbridge Township
00=Stock Transportation,Transportation,171.975000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK113]
BANKNAME=Business Woodbridge
00=National Golf Club of Canada ,Business,172.470000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK114]
BANKNAME=Event Medical Services
00=Spectrum Event Medical Services,EMS-Talk,172.590000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Spectrum Event Medical Services,EMS-Talk,172.980000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Spectrum Event Medical Services  on site,EMS-Tac,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK115]
BANKNAME=125 M Band
00=VE3RSD  Oakville,Ham,224.240000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=VE3RSD  Brampton  IRLP ,Ham,224.240000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=VA3WHQ  SSPBD Network,Ham,224.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=VE3WIK  Hamilton,Ham,224.520000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=VE3RSD  Mississauga  IRLP,Ham,224.620000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=VE3PAQ  Acton,Ham,224.720000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=VE3RSB  Burlington,Ham,224.740000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=VE3BEG  Uxbridge,Ham,224.860000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=VE3WIK  Carlisle,Ham,224.960000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK116]
BANKNAME=Veridian Connections
00=Veridian Connections Paging  ,Utilities,407.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Veridian Connections Operations,Utilities,412.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Veridian Connections Paging ,Utilities,412.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK117]
BANKNAME=Business Etobicoke
00=Swifttrans Airport Shuttle,Transportation,407.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Holiday Inn  Airport,Business,408.012500,FM,15k,OFF,250KHz,OFF,OFF,115
02=CBRE Facilities Management  Resources Road Complex ,Business,410.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=CF Sherway Gardens  Property Management,Business,452.062500,FM,15k,OFF,250KHz,OFF,OFF,3
04=Albion Centre,Security,452.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=CF Sherway Gardens  Security,Security,452.362500,FM,15k,OFF,250KHz,OFF,OFF,3
06=Woodbine Centre  Security,Security,452.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Woodbine Centre  Property Management,Business,452.812500,FM,15k,OFF,250KHz,OFF,OFF,311
08=Plant World,Business,462.500000,FM,15k,OFF,250KHz,OFF,OFF,612
09=Cloverdale Mall,Security,462.825000,FM,15k,OFF,250KHz,OFF,OFF,261
10=Home Depot  1983 Kipling Ave,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,754

[BANK118]
BANKNAME=Peel Region Attractions Powerade Centre
00=Centre 1,Business,408.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Centre 2,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Centre 3,Business,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Centre 4,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK119]
BANKNAME=Markham 
00=Markham Stouffville Hospital  Security,Security,408.537500,FM,15k,OFF,250KHz,OFF,OFF,031
01=Markham Stouffville Hospital  Maintenance,Hospital,452.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK120]
BANKNAME=  Ryerson University
00=Site 001 Ryerson,TRS,409.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Ryerson,TRS,409.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Ryerson,TRS,409.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK121]
BANKNAME=  Metrolinx  GO Transit
00=Site 001 East Simulcast,TRS,410.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 East Simulcast,TRS,410.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 006 Uxbridge,TRS,410.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 East Simulcast,TRS,410.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 East Simulcast,TRS,410.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 002 West Simulcast,TRS,410.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 006 Uxbridge,TRS,410.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 002 West Simulcast,TRS,411.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 East Simulcast,TRS,411.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 East Simulcast,TRS,411.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 East Simulcast,TRS,411.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 East Simulcast,TRS,412.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 002 West Simulcast,TRS,413.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 001 East Simulcast,TRS,413.462500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 002 West Simulcast,TRS,413.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 001 East Simulcast,TRS,413.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 002 West Simulcast,TRS,413.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 001 East Simulcast,TRS,413.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 002 West Simulcast,TRS,413.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 002 West Simulcast,TRS,413.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 006 Uxbridge,TRS,413.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK122]
BANKNAME=  McMaster University
00=Site 001 MAC,TRS,410.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 MAC,TRS,412.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 MAC,TRS,461.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 MAC,TRS,462.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 MAC,TRS,463.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK123]
BANKNAME=  Alectra Utilities
00=Site 005 Markham,TRS,410.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 006 Richmond Hill,TRS,410.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 004 Vaughan,TRS,413.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK124]
BANKNAME=Business North York
00=CBRE Facilities Management  Wilson Complex  Ministry of Transportation ,Business,410.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Holiday Inn  Yorkdale  Housekeeping Paging,Business,452.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=The Oaks  Property Management  Chalkfarm Drive,Business,452.362500,FM,15k,OFF,250KHz,OFF,OFF,023
03=Fairview Mall,Security,452.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=JaneFinch Mall,Security,453.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Lawrence Square Mall,Security,460.925000,FM,15k,OFF,250KHz,OFF,OFF,40
06=Toronto Emergency Services  4300 Dufferin St  Maintenance,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Shops at Don Mills,Security,460.925000,FM,15k,OFF,250KHz,OFF,OFF,115
08=Fairview Mall  Property Management,Business,463.850000,FM,15k,OFF,250KHz,OFF,OFF,412

[BANK125]
BANKNAME=Business Downtown
00=CBRE Facilities Management  Mowat Block,Business,410.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=City of Toronto Properties  Security Ch 1,Security,410.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Union Station  Security Office,Security,410.562500,FM,15k,OFF,250KHz,OFF,OFF,411
03=City of Toronto Properties  Security Ch 2,Security,412.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=VIA Rail Canada  Union Station Porters,Business,451.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=KoolHaus,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,365
06=Delta Chelsea Hotel,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,026
07=Hazelton Lanes,Business,452.362500,FM,15k,OFF,250KHz,OFF,OFF,412
08=Sheraton Centre,Business,452.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Hotel InterContinental,Business,452.812500,FM,15k,OFF,250KHz,OFF,OFF,413
10=77 Bloor Street West  Property Management,Business,452.812500,FM,15k,OFF,250KHz,OFF,OFF,065
11=The Crossways  Property Management,Business,452.812500,FM,15k,OFF,250KHz,OFF,OFF,116
12=Cumberland Terrace  Security,Security,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=2 Bloor Street West  Property Management,Business,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Cumberland Terrace  Property Management,Business,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Commerce Court Ch 2,Security,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Richmond  Adelaide Centre  Property Management,Business,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Atrium On Bay  Security,Security,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Four Seasons Hotel,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Delta Chelsea Hotel,Business,456.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Commerce Court Ch 1,Security,460.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=Town Inn Suites,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,043
22=Atrium on Bay  Property Management,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=2 Bloor Street East,Business,462.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=Carlton Tower,Security,462.825000,FM,15k,OFF,250KHz,OFF,OFF,244
25=Royal Bank Plaza  Security,Security,463.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=ShangriLa Hotel  Security,Security,464.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK126]
BANKNAME=Attractions Core
00=Royal Ontario Museum  City of Toronto Security,Security,410.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Harbourfront Centre,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,155
02=Art Gallery of Ontario ,Security,452.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=YongeDundas Square  Security Simplex 2,Security,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Harbourfront Centre,Business,454.200000,FM,15k,OFF,250KHz,OFF,OFF,155
05=Metro Toronto Convention Centre Security,Security,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Metro Toronto Convention Centre Shuttle,Transportation,460.925000,FM,15k,OFF,250KHz,OFF,OFF,143
07=Harbourfront Centre,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,155
08=YongeDundas Square  Security ,Security,462.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=YongeDundas Square  Security Simplex 1 ,Security,465.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK127]
BANKNAME=  The Hospital For Sick Children
00=Site 001 HSC,TRS,410.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK128]
BANKNAME=Ontario Power Generation  Darlington
00=Ontario Power Generation  Darlington ,Utilities,410.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK129]
BANKNAME=Ontario Power Generation
00=OPG  800 Kipling Avenue,Utilities,410.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK130]
BANKNAME=  Toronto South Detention Centre
00=Site 001 Toronto South DC,TRS,410.931250,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Toronto South DC,TRS,411.456250,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Toronto South DC,TRS,411.906250,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK131]
BANKNAME=Uxbridge 
00=Town Roads Department,Public Works,411.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK132]
BANKNAME=Oakville
00=Hydro Ch 1  TG 100,Utilities,411.412500,FM,15k,OFF,250KHz,OFF,OFF,40
01=Hydro Ch 2  Stringing,Utilities,411.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Works Department,Public Works,412.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Parks  Rec,Public Works,412.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=The Marquee  Bouncer Office,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,143
05=Oakville Trafalgar Memorial Hospital ,Hospital,452.812500,FM,15k,OFF,250KHz,OFF,OFF,315
06=The Marquee  Low Power,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=The Marquee  Bouncer Talkaround,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,143
08=Syl Apps Youth Treatment Centre  Kinark Services,Corrections,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Oakville Trafalgar Memorial Hospital ,Hospital,462.237500,FM,15k,OFF,250KHz,OFF,OFF,051

[BANK133]
BANKNAME=  KELCOM Toronto
00=Site 001 CN Tower,TRS,411.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 CN Tower,TRS,413.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 CN Tower,TRS,413.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK134]
BANKNAME=  FleetConnect 
00=Site 012 Toronto,TRS,411.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 011 Hamilton,TRS,420.075000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 011 Hamilton,TRS,420.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 011 Hamilton,TRS,420.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 010 Milton,TRS,420.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 010 Milton,TRS,420.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 010 Milton,TRS,420.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 012 Toronto,TRS,451.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 014 Blackstock,TRS,453.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 014 Blackstock,TRS,453.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 012 Toronto,TRS,454.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 013 King City,TRS,460.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 013 King City,TRS,461.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 012 Toronto,TRS,462.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 014 Blackstock,TRS,462.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 014 Blackstock,TRS,463.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 013 King City,TRS,463.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK135]
BANKNAME=Correctional Facilities
00=Toronto East Detention Centre,Corrections,411.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK136]
BANKNAME=Ontario Government Agencies
00=Hamilton Wentworth Detention Centre,Corrections,411.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Hamilton Wentworth Detention Centre,Corrections,412.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK137]
BANKNAME=Newmarket
00=Newmarket  Tay Power Distribution,Utilities,412.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Town Public Works Dept,Public Works,463.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK138]
BANKNAME=McMaster University Medical Centre
00=Security and Parking,Security,412.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Security and Parking,Security,451.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK139]
BANKNAME=Ontario Shores Centre for Mental Health Sciences
00=Ontario Shores Centre for Mental Health Sciences,Hospital,413.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Ontario Shores Centre for Mental Health Sciences,Hospital,415.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Ontario Shores Centre for Mental Health Sciences,Hospital,418.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Ontario Shores Centre for Mental Health Sciences  Paging,Hospital,464.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK140]
BANKNAME=Brampton
00= Roy McMurtry Youth Centre ,Corrections,413.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Corporate Properties,Public Works,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Corporate Properties,Public Works,453.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Corporate Properties,Public Works,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Corporate Properties,Public Works,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Corporate Properties,Public Works,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Brampton Civic Hospital  Portering,Hospital,864.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Brampton Civic Hospital  Housekeeping,Hospital,865.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Brampton Civic Hospital  Security,Security,865.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK141]
BANKNAME=Toronto Hydro Electric System
00=Toronto Hydro Electric System  Underground,Utilities,413.537500,FM,15k,OFF,250KHz,OFF,OFF,023

[BANK142]
BANKNAME=Caledon Fire  Emergency Services
00=Fire  Station 302 Dispatch,Data,414.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK143]
BANKNAME=Mississauga Fire Service
00=Station Dispatch,Fire Dispatch,414.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Talkaround,Fire-Tac,851.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Talkaround,Fire-Tac,851.625000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Talkaround,Fire-Tac,852.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Talkaround,Fire-Tac,852.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Vehicular Repeater,Fire Dispatch,859.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK144]
BANKNAME=  Fairmont Royal York Hotel
00=Site 001 Royal York Hotel,TRS,420.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Royal York Hotel,TRS,420.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Royal York Hotel,TRS,420.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Royal York Hotel,TRS,420.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK145]
BANKNAME=  Suncor Energy Mississauga
00=Site 001 Suncor Energy,TRS,420.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Suncor Energy,TRS,420.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Suncor Energy,TRS,420.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Suncor Energy,TRS,420.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK146]
BANKNAME=  OLGC  Woodbine Racetrack Slots
00=Site 001 OLGC Woodbine,TRS,420.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 OLGC Woodbine,TRS,420.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 OLGC Woodbine,TRS,420.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 OLGC Woodbine,TRS,420.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK147]
BANKNAME=  OnQue
00=Site 003 Hamilton,TRS,420.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 003 Hamilton,TRS,420.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 003 Hamilton,TRS,420.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 003 Hamilton,TRS,420.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 003 Hamilton,TRS,420.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 CN Tower,TRS,422.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 CN Tower,TRS,422.206250,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 CN Tower,TRS,422.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 004 Clarington,TRS,422.218750,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 007 Scarborough,TRS,422.231250,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 CN Tower,TRS,422.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 CN Tower,TRS,422.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 001 CN Tower,TRS,422.306250,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 001 CN Tower,TRS,422.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 008 Aurora,TRS,422.318750,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 001 CN Tower,TRS,422.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 001 CN Tower,TRS,422.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 001 CN Tower,TRS,422.406250,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 001 CN Tower,TRS,422.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 004 Clarington,TRS,422.418750,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 006 Milton,TRS,422.431250,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=Site 001 CN Tower,TRS,422.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=Site 001 CN Tower,TRS,422.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=Site 001 CN Tower,TRS,422.506250,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=Site 001 CN Tower,TRS,422.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=Site 008 Aurora,TRS,422.518750,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=Site 007 Scarborough,TRS,422.531250,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=Site 001 CN Tower,TRS,422.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=Site 001 CN Tower,TRS,422.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=Site 001 CN Tower,TRS,422.606250,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=Site 001 CN Tower,TRS,422.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF
31=Site 008 Aurora,TRS,422.618750,FM,15k,OFF,250KHz,OFF,OFF,OFF
32=Site 006 Milton,TRS,422.631250,FM,15k,OFF,250KHz,OFF,OFF,OFF
33=Site 001 CN Tower,TRS,422.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
34=Site 006 Milton,TRS,422.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
35=Site 004 Clarington,TRS,422.968750,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK148]
BANKNAME=  Rogers Centre
00=Site 001 001,TRS,420.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 001,TRS,420.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 001,TRS,420.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 001,TRS,420.850000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 001,TRS,420.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK149]
BANKNAME=  Talk Wireless LTR UHF
00=Site 001 Hamilton,TRS,420.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK150]
BANKNAME=  RCMP O Division
00=Site 036 Ballantrae,TRS,421.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 016 Toronto  West ,TRS,421.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 017 Toronto  East,TRS,421.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 035 Hamilton,TRS,421.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 041 Clarington,TRS,421.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 004 Newmarket,TRS,421.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 024 Toronto  South,TRS,421.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 041 Clarington,TRS,421.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 016 Toronto  West ,TRS,421.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 004 Newmarket,TRS,421.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 023 Airway Centre  Toronto Pearson Airport,TRS,421.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 035 Hamilton,TRS,421.425000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 023 Airway Centre  Toronto Pearson Airport,TRS,421.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 041 Clarington,TRS,421.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 024 Toronto  South,TRS,421.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 035 Hamilton,TRS,421.575000,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 017 Toronto  East,TRS,421.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 016 Toronto  West ,TRS,421.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 024 Toronto  South,TRS,421.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 027 Milton,TRS,421.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 035 Hamilton,TRS,421.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=Site 023 Airway Centre  Toronto Pearson Airport,TRS,421.875000,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=Site 016 Toronto  West ,TRS,421.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=Site 009 King City,TRS,421.975000,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=Site 027 Milton,TRS,422.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=Site 009 King City,TRS,422.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=Site 027 Milton,TRS,422.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=Site 017 Toronto  East,TRS,422.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=Site 023 Airway Centre  Toronto Pearson Airport,TRS,422.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=Site 009 King City,TRS,422.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=Site 024 Toronto  South,TRS,422.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
31=Site 017 Toronto  East,TRS,423.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK151]
BANKNAME=  Mobile Business  Toronto LTR  B
00=Site 001 2 Bloor St E,TRS,422.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 2 Bloor St E,TRS,422.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 2 Bloor St E,TRS,422.387500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 2 Bloor St E,TRS,422.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 2 Bloor St E,TRS,422.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 2 Bloor St E,TRS,422.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK152]
BANKNAME=  Mobile Business  Hamilton 420 MHz
00=Site 001 Confirmed LCN,TRS,422.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Confirmed LCN,TRS,422.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Confirmed LCN,TRS,422.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Confirmed LCN,TRS,422.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Confirmed LCN,TRS,422.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Confirmed LCN,TRS,422.625000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Confirmed LCN,TRS,422.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK153]
BANKNAME=  Toronto Transit Commission PowerTrunk
00=Site 001 Toronto,TRS,422.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Toronto,TRS,422.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Toronto,TRS,422.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Toronto,TRS,422.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Toronto,TRS,422.425000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Toronto,TRS,422.462500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Toronto,TRS,422.525000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 Toronto,TRS,422.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 Toronto,TRS,422.625000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 Toronto,TRS,422.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 Toronto,TRS,422.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 Toronto,TRS,422.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK154]
BANKNAME=  Point to Point
00=Site 002 King City,TRS,422.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 002 King City,TRS,422.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 002 King City,TRS,422.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK155]
BANKNAME=TTC  CIS 
00=22  CN Tower,Transportation,423.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=33  Finch ,Transportation,423.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=35  Arrow ,Transportation,423.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=36  Malvern,Transportation,423.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=37  Hillcrest ,Transportation,423.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=38  Greenwood ,Transportation,423.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=39  Wilson ,Transportation,423.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=40  Pharmacy,Transportation,423.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=41  Shipp,Transportation,423.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=42  Birchmount ,Transportation,423.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=43  Davisville,Transportation,423.762500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK156]
BANKNAME=  DMRMARC Ontario Amateur Repeater Network
00=Site 302321 VA3XFT Toronto,TRS,441.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 302319 VE3OBI Raglan,TRS,442.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 302303 VA3XPR Toronto,TRS,442.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 302315 VE3UHM Hamilton,TRS,444.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK157]
BANKNAME=70 cm Band
00=VE3ULR  Aurora,Ham,442.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=VE3RPT  Uxbridge,Ham,442.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=VE3PAQ  Acton,Ham,442.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=VA3UKW  Toronto,Ham,442.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=VA3ODX  Burlington  Echolink,Ham,442.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=VA3CTR  Unionville,Ham,442.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=VE3HAL  Milton,Ham,442.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=VA3GTU  Toronto,Ham,442.375000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=VE3OKR  Oakville,Ham,442.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=VA3URU  Ballantrae,Ham,442.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=VE3RDM  Hamilton,Ham,442.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=VE3UHM  Hamilton,Ham,442.525000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=VE3GIV  Hamilton,Ham,442.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=VE3CAY  Toronto,Ham,442.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=VA3GTU  Toronto,Ham,442.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=VE3YYZ   DSTAR  Toronto,Ham,442.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=VE3WOO  Toronto,Ham,442.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=VA3GTU  Etobicoke,Ham,442.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=VA3GTU  Etobicoke,Ham,442.800000,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=VA3GTU  Acton,Ham,442.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=VE3SNM  Ballantrae,Ham,442.850000,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=VA3GTU  Toronto,Ham,442.975000,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=VE3NAA  Oshawa,Ham,443.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=VA3SCR  Toronto,Ham,443.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=VE3YYZ  Toronto,Ham,443.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=VE3ZOE  Hamilton,Ham,443.075000,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=VE3SKI  Toronto,Ham,443.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=VE3RAK  Toronto,Ham,443.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=VE3BUR  Burlington,Ham,443.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=VA3BUR  Southwest  Aldershot  Hamilton ,Ham,443.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=VE3RFI,Ham,443.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
31=VA3PWR  Newmarket,Ham,443.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
32=VE3VOP  Toronto,Ham,443.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
33=VE3RTC  Scarborough,Ham,443.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
34=VA3HR  Milton  Halton ARES,Ham,443.425000,FM,15k,OFF,250KHz,OFF,OFF,OFF
35=VE3WOM  Whitby,Ham,443.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
36=VE3NIB  Toronto,Ham,443.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
37=VE3PRC  Brampton,Ham,443.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
38=VE3UPR,Ham,443.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
39=VE3NOR  Toronto,Ham,443.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF
40=VE3WIK  Carlisle,Ham,443.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
41=VA3BAL  Ballantrae,Ham,443.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
42=VA3GTU  Scarborough,Ham,443.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF
43=VE3JOP  Vaughan,Ham,443.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
44=VA3PMO  Mississauga,Ham,443.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
45=VA3TVB  Scarborough,Ham,443.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
46=VE3OBN   Toronto,Ham,443.900000,FM,15k,OFF,250KHz,OFF,OFF,OFF
47=VE3ZRB  Halton Hills,Ham,443.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
48=VE3UHM  Hamilton DMR,Ham,444.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
49=VE3NCF  Hamilton,Ham,444.075000,FM,15k,OFF,250KHz,OFF,OFF,OFF
50=VE3WDX  Aurora,Ham,444.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
51=VE3WOO  Caledon,Ham,444.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
52=VE3YRC  Richmond Hill,Ham,444.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
53=VE3OAK  Oakville ,Ham,444.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
54=VE3WOQ  Whitby,Ham,444.375000,FM,15k,OFF,250KHz,OFF,OFF,OFF
55=VE3TWR  Toronto,Ham,444.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF
56=VA3BMI  Toronto,Ham,444.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
57=VE3URU  Toronto,Ham,444.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
58=VE3YRK DSTAR,Ham,444.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
59=VE3OBI  Raglan,Ham,444.525000,FM,15k,OFF,250KHz,OFF,OFF,OFF
60=VE3MIS  Mississauga,Ham,444.575000,FM,15k,OFF,250KHz,OFF,OFF,OFF
61=VE3DAX  Pickering,Ham,444.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
62=VA3ATL  Toronto,Ham,444.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
63=VE3RSB  Burlington ,Ham,444.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
64=VE3UKW  Toronto,Ham,444.850000,FM,15k,OFF,250KHz,OFF,OFF,OFF
65=VA3OPR  Brampton,Ham,444.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK158]
BANKNAME=  BrandMeister Canada Amateur Repeater Network
00=Site 302327 VE3OUR Durham,TRS,442.875000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 302321 VE3YYZ Toronto,TRS,444.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK159]
BANKNAME=Media Oshawa
00=CKDO Studio Link,Media,450.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK160]
BANKNAME=Media Shaw Media
00=Global News Helicopter CFMTE,Media,450.975000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK161]
BANKNAME=Mississauga
00=Community Centre Operations Ch1 ,Public Works,451.012500,FM,15k,OFF,250KHz,OFF,OFF,743
01=Gordon Graydon Memorial SS  Ch 1 Administration,Schools,454.225000,FM,15k,OFF,250KHz,OFF,OFF,411
02=StGonzaga Secondary SchoolErin Meadows Community Centre,Schools,460.237500,FM,15k,OFF,250KHz,OFF,OFF,631
03=Community Centre Operations Ch2,Public Works,462.675000,FM,15k,OFF,250KHz,OFF,OFF,743
04=Gordon Graydon Memorial SS  Ch 2 MaintenanceCustodial,Schools,469.262500,FM,15k,OFF,250KHz,OFF,OFF,411

[BANK162]
BANKNAME=  Mobile Business Communications 
00=Site 001 CN Tower,TRS,451.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 CN Tower,TRS,452.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 CN Tower,TRS,453.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 CN Tower,TRS,454.462500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 CN Tower,TRS,463.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 CN Tower,TRS,463.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK163]
BANKNAME=  Purolator
00=Site 001 Ontario Hub,TRS,451.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Ontario Hub,TRS,452.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Ontario Hub,TRS,452.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK164]
BANKNAME=  GOTRBO Network
00=Site 011 Fennell,TRS,451.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 007 CN Tower,TRS,451.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 007 CN Tower,TRS,452.487500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 004 Ballantrae,TRS,452.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 006 Clarington,TRS,452.862500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 006 Clarington,TRS,452.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 004 Ballantrae,TRS,453.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 007 CN Tower,TRS,453.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 011 Fennell,TRS,453.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 011 Fennell,TRS,460.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 007 CN Tower,TRS,462.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 007 CN Tower,TRS,463.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK165]
BANKNAME=FirstOntario Centre Operations
00=Operations,Business,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Centre Events,Business,451.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=FirstOntario TG 2,Business,451.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=FirstOntario TG 4,Business,451.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=HP Events,Business,451.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=FirstOntario TG 3,Business,451.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Administration,Business,452.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=HP Stage,Business,453.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Emergency,Business,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Bulldogs,Business,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Dispatch,Business,462.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK166]
BANKNAME=Attractions Etobicoke
00=Woodbine Race Track  Champions ,Business,451.187500,FM,15k,OFF,250KHz,OFF,OFF,172
01=OLG Slots Security ,Security,451.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Woodbine Race Track  Maintenance ,Business,452.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Woodbine Race Track  Officials,Business,462.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Woodbine Race Track  Guest Services,Business,463.850000,FM,15k,OFF,250KHz,OFF,OFF,662

[BANK167]
BANKNAME=  Metro Toronto Convention Centre
00=Site 001 MTCC,TRS,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 MTCC,TRS,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK168]
BANKNAME=Business Scarborough
00=Malvern Town Centre,Security,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Parkway Mall,Security,451.187500,FM,15k,OFF,250KHz,OFF,OFF,152
02=The Greens at Tam OShanter  Condo Security,Business,458.725000,FM,15k,OFF,250KHz,OFF,OFF,031

[BANK169]
BANKNAME=  OLGC  Mohawk Racetrack Slots
00=Site 001 Site 1,TRS,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Site 1,TRS,452.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK170]
BANKNAME=Environment Canada 4905 Dufferin Street
00=In House  Security,Security,451.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=In House  Emergency,Emergency Ops,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK171]
BANKNAME=Federal Offices Hamilton
00=CRA Security,Security,451.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=CRA Security ,Security,452.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=EC  Canadian Centre Inland Waters,Federal,456.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=EC  Canadian Centre Inland Waters,Federal,464.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK172]
BANKNAME=  University of Toronto
00=Site 001 55 Harbord Street,TRS,451.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 55 Harbord Street,TRS,452.975000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 55 Harbord Street,TRS,464.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK173]
BANKNAME=Hatzoloh Toronto 
00=Dispatch,EMS Dispatch,451.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK174]
BANKNAME=Healthcare North York Branson Urgent Care 
00=Maintenance,Hospital,451.662500,FM,15k,OFF,250KHz,OFF,OFF,263
01=Security,Security,461.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK175]
BANKNAME=Healthcare Scarborough Hospital  General and Grace sites 
00=Security,Security,451.662500,FM,15k,OFF,250KHz,OFF,OFF,205
01=Maintenance,Hospital,460.925000,FM,15k,OFF,250KHz,OFF,OFF,205
02=Security,Security,462.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK176]
BANKNAME=Flamboro Downs Slots Flamborough
00=Slot Technicians,Business,451.662500,FM,15k,OFF,250KHz,OFF,OFF,165
01=Emergency,Business,453.262500,FM,15k,OFF,250KHz,OFF,OFF,071
02=Track Security,Security,464.100000,FM,15k,OFF,250KHz,OFF,OFF,315
03=Food Service,Business,464.312500,FM,15k,OFF,250KHz,OFF,OFF,503
04=Valet,Business,464.337500,FM,15k,OFF,250KHz,OFF,OFF,115
05=Customer Service,Business,464.537500,FM,15k,OFF,250KHz,OFF,OFF,143

[BANK177]
BANKNAME=Healthcare Sunnybrook Health Sciences Centre
00=Security 2,Security,451.662500,FM,15k,OFF,250KHz,OFF,OFF,412
01=Security 1,Security,453.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK178]
BANKNAME=West 5th Campus
00=Security,Security,451.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK179]
BANKNAME=  National Communications Site Services DMR
00=Site 002 Area 2,TRS,451.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 000 Area 0,TRS,460.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 000 Area 0,TRS,462.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 002 Area 2,TRS,464.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK180]
BANKNAME=  Sheridan College Oakville
00=Site 001 Sheridan,TRS,451.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK181]
BANKNAME=  Maple Lodge Farms
00=Site 001 Brampton,TRS,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Brampton,TRS,452.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Brampton,TRS,460.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK182]
BANKNAME=Business Thornhill
00=Glen Park Apartments  Property Maintenance ,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,023
01=Glen Park Apartments  Property Security,Security,452.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=The Promenade  Security ,Security,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK183]
BANKNAME=  Humber College
00=Site 001 North Campus,TRS,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 North Campus,TRS,453.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 North Campus,TRS,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK184]
BANKNAME=Healthcare Holland Bloorview Childrens Rehabilitaion Centre
00=Operations,Hospital,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK185]
BANKNAME=Education Clarington
00=Charles Bowman Public School,Schools,451.787500,FM,15k,OFF,250KHz,OFF,OFF,026
01=St Elizabeth Catholic School,Schools,452.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=John M James Public School,Schools,453.700000,FM,15k,OFF,250KHz,OFF,OFF,754
03=Harold Longworth Public School,Schools,468.150000,FM,15k,OFF,250KHz,OFF,OFF,116
04=St Stephen Catholic Secondary School,Schools,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK186]
BANKNAME=Canadas Wonderland Vaughan
00=Ch 9  Speedcity Raceway,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Ch 4  Entertainment Theatre Group Sales Administration Marketing Finance,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Ch 1  Park Safety and Security,Security,460.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Ch 2  Attractions Maintenance Ecology and Utility,Business,461.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Ch 3  Resale and Admissions,Business,462.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK187]
BANKNAME=Healthcare Michael Garron Hospital
00=Security ,Security,451.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Security ,Security,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK188]
BANKNAME=Attractions Oshawa Ski Club
00=BrimacombeOshawa Ski Club Ch 2,Business,451.787500,FM,15k,OFF,250KHz,OFF,OFF,526
01=BrimacombeOshawa Ski Club Ch 3,Business,462.237500,FM,15k,OFF,250KHz,OFF,OFF,526
02=BrimacombeOshawa Ski Club Ch 1,Business,464.637500,FM,15k,OFF,250KHz,OFF,OFF,526

[BANK189]
BANKNAME=  National Communications Site Services Motorola
00=Site 001 Site1,TRS,451.850000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Site1,TRS,452.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Site1,TRS,452.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK190]
BANKNAME=  ICOM Canada 
00=Site 009 Hamilton,TRS,451.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 009 Hamilton,TRS,452.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 003 Toronto,TRS,452.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 003 Toronto,TRS,452.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 003 Toronto,TRS,453.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 009 Hamilton,TRS,462.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 004 Ballantrae,TRS,463.387500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK191]
BANKNAME=Mohawk College
00=Security,Security,451.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK192]
BANKNAME=Healthcare North York General
00=Security,Security,452.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK193]
BANKNAME=  University Health Network  Toronto General Hospital
00=Site 001 Toronto General Hospital,TRS,452.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK194]
BANKNAME=Golf and Country Clubs Hamilton Golf and Country Club
00=Security  Fairway Grooming,Business,452.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK195]
BANKNAME=  Porter Airlines
00=Site 001 Billy Bishop Toronto Island Airport,TRS,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Billy Bishop Toronto Island Airport,TRS,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK196]
BANKNAME=  CF Toronto Eaton Centre
00=Site 001 Eaton Centre,TRS,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Eaton Centre,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK197]
BANKNAME=Golf Beacon Hall Golf Club
00=Gatehouse and Valet,Business,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Operations,Business,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK198]
BANKNAME=  Ritz Carlton Hotel
00=Site 001 Ritz Carlton Hotel,TRS,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Ritz Carlton Hotel,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Ritz Carlton Hotel,TRS,457.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Ritz Carlton Hotel,TRS,459.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK199]
BANKNAME=  Oshawa Centre
00=Site 001 Oshawa Centre,TRS,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK200]
BANKNAME=  FedEx Pearson International Distribution
00=Site 001 FedEx PIA,TRS,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 FedEx PIA,TRS,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 FedEx PIA,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 FedEx PIA,TRS,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK201]
BANKNAME=  Toronto Zoo
00=Site 001 Toronto Zoo,TRS,452.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Toronto Zoo,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Toronto Zoo,TRS,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK202]
BANKNAME=Education York University
00=Keele Campus Security ,Security,452.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Keele Campus Security ,Security,457.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Seneca  York  Campus Security,Security,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Glendon Campus Security ,Security,461.987500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Keele Campus Parking Enforcement,Law Talk,462.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK203]
BANKNAME=  Pickering Town Centre
00=Site 001 PTC,TRS,452.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK204]
BANKNAME=  Federal Marine Terminals
00=Site 001 Terminal,TRS,452.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK205]
BANKNAME=Education Ontario College of Art and Design
00=Operations,Schools,453.087500,FM,15k,OFF,250KHz,OFF,OFF,051
01=Security,Security,462.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK206]
BANKNAME=  Communitronics
00=Site 001 Confirmed LCN,TRS,453.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Confirmed LCN,TRS,454.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK207]
BANKNAME=Healthcare St Michaels Hospital
00=Security,Security,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK208]
BANKNAME=Healthcare Rouge Valley  Centennary Hospital
00=Security,Security,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK209]
BANKNAME=Attractions Great Blue Heron Charity Casino  Port Perry
00=Great Blue Heron Charity Casino F2,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Great Blue Heron Charity Casino F3,Business,453.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Great Blue Heron Charity Casino F1,Business,453.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Great Blue Heron Charity Casino F4,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK210]
BANKNAME=Peel Region Attractions Hershey Centre
00=Channel 2,Business,453.450000,FM,15k,OFF,250KHz,OFF,OFF,703
01=Channel 1,Business,456.187500,FM,15k,OFF,250KHz,OFF,OFF,703
02=Channel 3,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,703
03=Channel 4,Business,458.700000,FM,15k,OFF,250KHz,OFF,OFF,703

[BANK211]
BANKNAME=Attractions Jungle Cat World Wildlife Park
00=Jungle Cat World Wildlife Park,Business,453.725000,FM,15k,OFF,250KHz,OFF,OFF,734

[BANK212]
BANKNAME=Media Canadian Broadcasting Corporation  Broadcast Centre
00=CBC News,Media,453.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK213]
BANKNAME=  Ford Motor Company Oakville 
00=Site 001 Oakville,TRS,453.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Oakville,TRS,461.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Oakville,TRS,461.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Oakville,TRS,463.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK214]
BANKNAME=Attractions Scarborough
00=Security Backup,Security,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Toronto Zoo  Simplex,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK215]
BANKNAME=  Trillium Health Partners
00=Site 003 Mississauga Hospital,TRS,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 003 Credit Valley Hospital ,TRS,461.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK216]
BANKNAME=  Sheridan College Peel Region
00=Site 002 Hazel McCallion Campus,TRS,453.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Davis Campus,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK217]
BANKNAME=  Magna Karmax 
00=Site 001 Milton,TRS,453.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Milton,TRS,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK218]
BANKNAME=  Billy Bishop Toronto City Airport
00=Site 001 Toronto Island,TRS,454.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Toronto Island,TRS,461.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK219]
BANKNAME=Juravinski Hospital
00=Juravinski Hospital ,Hospital,454.125000,FM,15k,OFF,250KHz,OFF,OFF,1
01=Juravinski Hospital  Security,Security,858.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Juravinski Hospital  Security,Security,858.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK220]
BANKNAME=  Exhibition Place
00=Site 001 Exhibition Place,TRS,454.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Exhibition Place,TRS,461.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Exhibition Place,TRS,463.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Exhibition Place,TRS,463.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK221]
BANKNAME=  CRH Canada  Holcim
00=Site 001 Mississauga,TRS,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK222]
BANKNAME=  OLGC  Ajax Downs Racetrack Slots
00=Site 001 Ajax Downs,TRS,454.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Ajax Downs,TRS,463.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK223]
BANKNAME=Chedoke Campus
00=Chedoke Campus  Security,Security,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK224]
BANKNAME=Retail Brampton
00=Shoppers World Ch 1,Business,454.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Shoppers World Ch 2,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK225]
BANKNAME=  Honeywell Aerospace
00=Site 001 Mississauga,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Mississauga,TRS,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Mississauga,TRS,464.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK226]
BANKNAME=  Erin Mills Town Center
00=Site 001 Erin Mills,TRS,454.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Erin Mills,TRS,464.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK227]
BANKNAME=  Fleetcom DMR
00=Site 001 500 Duplex,TRS,454.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 500 Duplex,TRS,462.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 500 Duplex,TRS,463.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK228]
BANKNAME=Peel Region Attractions Meadowvale Theatre
00=Medowvale Theatre,Business,456.012500,FM,15k,OFF,250KHz,OFF,OFF,606

[BANK229]
BANKNAME=Attractions Rogers Centre
00=Stadium  Roof Control,Business,457.575000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Stadium  Roof Control,Business,460.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK230]
BANKNAME=Business Canada Computers
00=Red,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Yellow,Business,458.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Green,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Blue,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK231]
BANKNAME=  Manheim Auto Auctions
00=Site 001 Milton,TRS,460.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Milton,TRS,461.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK232]
BANKNAME=Business Armoured Car Transportation
00=Brinks Canada Armoured Cars,Security,460.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK233]
BANKNAME=  Roxul
00=Site 001 Milton,TRS,460.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Milton,TRS,461.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK234]
BANKNAME=  University Health Network  Toronto Western Hospital
00=Site 001 Toronto Western Hospital,TRS,460.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK235]
BANKNAME=Education George Brown College
00=St James Campus  Security,Security,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Casa Loma Campus  Security,Security,460.925000,FM,15k,OFF,250KHz,OFF,OFF,116

[BANK236]
BANKNAME=  Scarborough Town Centre
00=Site 001 STC,TRS,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK237]
BANKNAME=  MaRS Discovery Centre
00=Site 001 661 University Avenue,TRS,460.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK238]
BANKNAME=Malton
00=Ascension of Our Lord Secondary School ,Schools,460.237500,FM,15k,OFF,250KHz,OFF,OFF,532

[BANK239]
BANKNAME=Charlton Campus
00=St Josephs Health Care,Hospital,460.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=St Josephs Health Care,Hospital,460.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK240]
BANKNAME=  Air Transat 
00=Site 001 Terminal 3,TRS,460.875000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Terminal 3,TRS,461.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK241]
BANKNAME=Business Halton Hills
00=Toronto Premium Outlets,Business,461.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Toronto Premium Outlets,Business,469.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK242]
BANKNAME=Royal Botanical Gardens Operations
00=SecurityMain,Security,461.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Maintenance,Business,461.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Events,Business,461.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK243]
BANKNAME=Attractions Exhibition Place
00=Medieval Times Dinner and Tournament,Business,462.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK244]
BANKNAME=Retail Bramalea
00=Bramalea City Centre  Security,Security,462.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Bramalea City Centre  Best Buy,Business,469.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK245]
BANKNAME=DriveIn Theatre Sharon
00=Theatre Operations FRS Ch4,Business,462.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK246]
BANKNAME=  CF TorontoDominion Centre
00=Site 001 TD Centre,TRS,463.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 TD Centre,TRS,463.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK247]
BANKNAME=  College Park
00=Site 001 Toronto College Park,TRS,463.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK248]
BANKNAME=Lakeridge Health  Oshawa General Hospital
00=Lakeridge Health  Oshawa General,Hospital,464.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK249]
BANKNAME=Healthcare Trillium Health Centre  Queensway Ambulatory Centre
00=Security ,Security,464.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK250]
BANKNAME=Business Aurora
00=Diamond Landscaping ,Business,468.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK251]
BANKNAME=Ajax
00=Town of Ajax,Public Works,469.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK252]
BANKNAME=  Durham NextGen
00=Site 010 South,TRS,769.631250,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 010 South,TRS,769.881250,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 010 South,TRS,770.131250,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 010 North,TRS,770.206250,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 010 South,TRS,770.343750,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 010 East,TRS,770.381250,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 010 North,TRS,770.456250,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 010 North,TRS,770.706250,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 010 South,TRS,771.168750,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 010 North,TRS,771.206250,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 010 East,TRS,771.418750,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 010 South,TRS,771.456250,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 010 North,TRS,771.668750,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 010 East,TRS,772.443750,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 010 North,TRS,772.506250,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 010 South,TRS,772.756250,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 010 East,TRS,773.618750,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 010 North,TRS,773.843750,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 010 East,TRS,773.868750,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 010 East,TRS,774.118750,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 010 East,TRS,774.368750,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK253]
BANKNAME=  Toronto Emergency Services
00=Site 005 South,TRS,769.931250,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 005 South,TRS,770.181250,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 007 North,TRS,770.431250,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 007 North,TRS,770.506250,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 006 East,TRS,770.531250,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 005 South,TRS,770.556250,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 008 West,TRS,770.581250,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 006 East,TRS,770.606250,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 008 West,TRS,770.631250,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 005 South,TRS,770.681250,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 007 North,TRS,770.756250,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 006 East,TRS,770.781250,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 007 North,TRS,770.806250,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 008 West,TRS,770.831250,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 005 South,TRS,770.856250,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 006 East,TRS,770.881250,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 005 South,TRS,771.006250,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 007 North,TRS,771.031250,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 006 East,TRS,771.056250,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 008 West,TRS,771.081250,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 005 South,TRS,771.106250,FM,15k,OFF,250KHz,OFF,OFF,OFF
21=Site 005 South,TRS,771.256250,FM,15k,OFF,250KHz,OFF,OFF,OFF
22=Site 007 North,TRS,771.281250,FM,15k,OFF,250KHz,OFF,OFF,OFF
23=Site 006 East,TRS,771.306250,FM,15k,OFF,250KHz,OFF,OFF,OFF
24=Site 008 West,TRS,771.331250,FM,15k,OFF,250KHz,OFF,OFF,OFF
25=Site 005 South,TRS,771.356250,FM,15k,OFF,250KHz,OFF,OFF,OFF
26=Site 007 North,TRS,771.506250,FM,15k,OFF,250KHz,OFF,OFF,OFF
27=Site 006 East,TRS,771.531250,FM,15k,OFF,250KHz,OFF,OFF,OFF
28=Site 008 West,TRS,771.556250,FM,15k,OFF,250KHz,OFF,OFF,OFF
29=Site 005 South,TRS,771.581250,FM,15k,OFF,250KHz,OFF,OFF,OFF
30=Site 007 North,TRS,771.606250,FM,15k,OFF,250KHz,OFF,OFF,OFF
31=Site 008 West,TRS,772.393750,FM,15k,OFF,250KHz,OFF,OFF,OFF
32=Site 005 South,TRS,772.418750,FM,15k,OFF,250KHz,OFF,OFF,OFF
33=Site 005 South,TRS,772.668750,FM,15k,OFF,250KHz,OFF,OFF,OFF
34=Site 007 North,TRS,772.831250,FM,15k,OFF,250KHz,OFF,OFF,OFF
35=Site 008 West,TRS,772.881250,FM,15k,OFF,250KHz,OFF,OFF,OFF
36=Site 007 North,TRS,773.143750,FM,15k,OFF,250KHz,OFF,OFF,OFF
37=Site 005 South,TRS,773.168750,FM,15k,OFF,250KHz,OFF,OFF,OFF
38=Site 005 South,TRS,773.268750,FM,15k,OFF,250KHz,OFF,OFF,OFF
39=Site 006 East,TRS,773.318750,FM,15k,OFF,250KHz,OFF,OFF,OFF
40=Site 008 West,TRS,773.331250,FM,15k,OFF,250KHz,OFF,OFF,OFF
41=Site 007 North,TRS,773.393750,FM,15k,OFF,250KHz,OFF,OFF,OFF
42=Site 005 South,TRS,773.418750,FM,15k,OFF,250KHz,OFF,OFF,OFF
43=Site 005 South,TRS,773.518750,FM,15k,OFF,250KHz,OFF,OFF,OFF
44=Site 007 North,TRS,773.543750,FM,15k,OFF,250KHz,OFF,OFF,OFF
45=Site 006 East,TRS,773.581250,FM,15k,OFF,250KHz,OFF,OFF,OFF
46=Site 008 West,TRS,773.768750,FM,15k,OFF,250KHz,OFF,OFF,OFF
47=Site 005 South,TRS,773.793750,FM,15k,OFF,250KHz,OFF,OFF,OFF
48=Site 007 North,TRS,773.818750,FM,15k,OFF,250KHz,OFF,OFF,OFF
49=Site 005 South,TRS,774.018750,FM,15k,OFF,250KHz,OFF,OFF,OFF
50=Site 008 West,TRS,774.043750,FM,15k,OFF,250KHz,OFF,OFF,OFF
51=Site 007 North,TRS,774.068750,FM,15k,OFF,250KHz,OFF,OFF,OFF
52=Site 005 South,TRS,774.268750,FM,15k,OFF,250KHz,OFF,OFF,OFF
53=Site 008 West,TRS,774.293750,FM,15k,OFF,250KHz,OFF,OFF,OFF
54=Site 007 North,TRS,774.318750,FM,15k,OFF,250KHz,OFF,OFF,OFF
55=Site 005 South,TRS,774.318750,FM,15k,OFF,250KHz,OFF,OFF,OFF
56=Site 009 Rapid Transit ,TRS,868.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
57=Site 009 Rapid Transit ,TRS,868.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
58=Site 009 Rapid Transit ,TRS,868.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
59=Site 009 Rapid Transit ,TRS,868.387500,FM,15k,OFF,250KHz,OFF,OFF,OFF
60=Site 009 Rapid Transit ,TRS,868.625000,FM,15k,OFF,250KHz,OFF,OFF,OFF
61=Site 009 Rapid Transit ,TRS,868.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
62=Site 009 Rapid Transit ,TRS,868.762500,FM,15k,OFF,250KHz,OFF,OFF,OFF
63=Site 009 Rapid Transit ,TRS,868.887500,FM,15k,OFF,250KHz,OFF,OFF,OFF
64=Site 009 Rapid Transit ,TRS,868.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK254]
BANKNAME=  York Region 
00=Site 001 Site 1,TRS,770.318750,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Site 1,TRS,770.656250,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Site 1,TRS,771.143750,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Site 1,TRS,771.393750,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Site 1,TRS,772.368750,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Site 1,TRS,772.543750,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Site 1,TRS,772.693750,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 Site 1,TRS,772.793750,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 Site 1,TRS,772.943750,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 Site 1,TRS,773.293750,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 Site 1,TRS,773.643750,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK255]
BANKNAME=  Air Canada 
00=Site 001 Primary,TRS,851.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Primary,TRS,851.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Primary,TRS,851.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Primary,TRS,851.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Primary,TRS,851.375000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Primary,TRS,851.575000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Primary,TRS,851.775000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 Primary,TRS,851.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 Primary,TRS,852.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 Primary,TRS,852.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 Primary,TRS,852.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 Primary,TRS,852.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 001 Primary,TRS,852.825000,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 001 Primary,TRS,853.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 001 Primary,TRS,853.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK256]
BANKNAME=  Greater Toronto Airports Authority
00=Site 001 GTAA,TRS,851.075000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 GTAA,TRS,851.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 GTAA,TRS,851.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 GTAA,TRS,851.525000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 GTAA,TRS,851.700000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 GTAA,TRS,851.975000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 GTAA,TRS,852.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 GTAA,TRS,852.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 GTAA,TRS,852.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 GTAA,TRS,852.425000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 GTAA,TRS,852.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 GTAA,TRS,852.750000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK257]
BANKNAME=  US Steel Canada  Stelco 
00=Site 001 Site1,TRS,851.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Site1,TRS,851.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Site1,TRS,852.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Site1,TRS,852.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Site1,TRS,853.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Site1,TRS,853.075000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Site1,TRS,853.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK258]
BANKNAME=  Halton Region 
00=Site 002 North,TRS,857.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 South,TRS,857.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 002 North,TRS,857.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 002 North,TRS,857.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 South,TRS,857.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 002 North,TRS,857.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 South,TRS,859.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 002 North,TRS,859.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 South,TRS,859.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 002 North,TRS,859.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 South,TRS,860.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 South,TRS,861.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 002 North,TRS,861.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 001 South,TRS,862.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 001 South,TRS,862.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 001 South,TRS,862.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 002 North,TRS,863.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 002 North,TRS,867.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK259]
BANKNAME=  Hamilton 
00=Site 001 Hamilton,TRS,857.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Hamilton,TRS,857.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Hamilton,TRS,860.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Hamilton,TRS,861.812500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Hamilton,TRS,862.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Hamilton,TRS,866.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Hamilton,TRS,866.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 Hamilton,TRS,867.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 Hamilton,TRS,867.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 Hamilton,TRS,867.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 Hamilton,TRS,867.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 Hamilton,TRS,868.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK260]
BANKNAME=  Peel Region 
00=Site 001 Peel Region,TRS,866.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Peel Region,TRS,866.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Peel Region,TRS,866.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Peel Region,TRS,866.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Peel Region,TRS,866.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Peel Region,TRS,866.462500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Peel Region,TRS,866.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 Peel Region,TRS,866.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 Peel Region,TRS,866.712500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 Peel Region,TRS,866.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 Peel Region,TRS,866.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 001 Peel Region,TRS,866.962500,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 001 Peel Region,TRS,867.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 001 Peel Region,TRS,867.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 001 Peel Region,TRS,867.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 001 Peel Region,TRS,867.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 001 Peel Region,TRS,867.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 001 Peel Region,TRS,867.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 001 Peel Region,TRS,867.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 001 Peel Region,TRS,867.837500,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 001 Peel Region,TRS,867.937500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK261]
BANKNAME=Fire Services  Back Up
00=North Command,Fire-Tac,866.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=East Command,Fire-Tac,867.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=West Command,Fire-Tac,867.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=South Command,Fire-Tac,867.462500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Citywide,Fire-Tac,867.737500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK262]
BANKNAME=Fire Services  South Command
00=South Fireground 1 ,Fire-Tac,868.125000,FM,15k,OFF,250KHz,OFF,OFF,293
01=South Fireground 2,Fire-Tac,868.250000,FM,15k,OFF,250KHz,OFF,OFF,293
02=South Fireground 3,Fire-Tac,868.525000,FM,15k,OFF,250KHz,OFF,OFF,293
03=South Fireground 4,Fire-Tac,868.737500,FM,15k,OFF,250KHz,OFF,OFF,293
04=South Fireground 5,Fire-Tac,868.800000,FM,15k,OFF,250KHz,OFF,OFF,293
05=South Fireground 6 ,Fire-Tac,868.987500,FM,15k,OFF,250KHz,OFF,OFF,293

[BANK263]
BANKNAME=Fire Services  NorthEastWest Command
00=North East West Fireground 1,Fire-Tac,868.200000,FM,15k,OFF,250KHz,OFF,OFF,293
01=North East West Fireground 2,Fire-Tac,868.300000,FM,15k,OFF,250KHz,OFF,OFF,293
02=North East West Fireground 3,Fire-Tac,868.425000,FM,15k,OFF,250KHz,OFF,OFF,293
03=North East West Fireground 4,Fire-Tac,868.475000,FM,15k,OFF,250KHz,OFF,OFF,293
04=North East West Fireground 5,Fire-Tac,868.662500,FM,15k,OFF,250KHz,OFF,OFF,293
05=North East West Fireground 6,Fire-Tac,868.850000,FM,15k,OFF,250KHz,OFF,OFF,293

[BANK264]
BANKNAME=  Maple Leaf Sports and Entertainment
00=Site 001 Air Canada Centre,TRS,935.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Air Canada Centre,TRS,935.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Air Canada Centre,TRS,935.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Air Canada Centre,TRS,935.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Air Canada Centre,TRS,935.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK265]
BANKNAME=  Toronto Hydro and Works
00=Site 001 Toronto,TRS,936.637500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Toronto,TRS,936.675000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Toronto,TRS,936.687500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Toronto,TRS,938.387500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Toronto,TRS,938.437500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK266]
BANKNAME=  Toronto City Services
00=Site 001 Toronto City Services,TRS,936.650000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Toronto City Services,TRS,936.662500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Toronto City Services,TRS,936.875000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Toronto City Services,TRS,938.400000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Toronto City Services,TRS,938.412500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Toronto City Services,TRS,938.450000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK267]
BANKNAME=  Fleetcom
00=Site 001 500 Duplex Ave,TRS,936.900000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 500 Duplex Ave,TRS,936.912500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 500 Duplex Ave,TRS,936.925000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 500 Duplex Ave,TRS,936.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 500 Duplex Ave,TRS,937.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 500 Duplex Ave,TRS,937.525000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 500 Duplex Ave,TRS,937.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 500 Duplex Ave,TRS,937.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK268]
BANKNAME=  Mobile Business  Toronto LTR  A
00=Site 001 CN Tower,TRS,937.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 CN Tower,TRS,937.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 CN Tower,TRS,937.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 CN Tower,TRS,938.512500,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 CN Tower,TRS,938.537500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 CN Tower,TRS,938.562500,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 CN Tower,TRS,938.587500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 001 CN Tower,TRS,939.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 001 CN Tower,TRS,939.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 001 CN Tower,TRS,939.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 001 CN Tower,TRS,939.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK269]
BANKNAME=Healthcare Humber River Hospital  Wilson Site
00=Security,Security,937.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Security,Security,937.950000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK270]
BANKNAME=  Brampton City Services
00=Site 001 Brampton,TRS,937.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Brampton,TRS,937.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Brampton,TRS,937.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 Brampton,TRS,938.525000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Brampton,TRS,938.550000,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 Brampton,TRS,938.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 Brampton,TRS,939.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK271]
BANKNAME=  Brampton
00=Site 002 Site 2,TRS,937.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Site 1,TRS,939.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 Site 1,TRS,939.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 002 Site 2,TRS,939.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 Site 1,TRS,939.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK272]
BANKNAME=  Airtime Communications
00=Site 017 Site17,TRS,937.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 017 Site17,TRS,937.475000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 017 Site17,TRS,938.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 017 Site17,TRS,938.375000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 017 Site17,TRS,938.725000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK273]
BANKNAME=  Oakville City Services
00=Site 001 BronteRebecca,TRS,938.137500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 BronteRebecca,TRS,938.150000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 001 BronteRebecca,TRS,938.162500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 001 BronteRebecca,TRS,938.175000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 001 BronteRebecca,TRS,938.187500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 001 BronteRebecca,TRS,938.200000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 001 BronteRebecca,TRS,938.212500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 004 Rattlesnake Point,TRS,938.225000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 004 Rattlesnake Point,TRS,938.237500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 002 White Oaks  Sector 1,TRS,938.250000,FM,15k,OFF,250KHz,OFF,OFF,OFF
10=Site 002 White Oaks  Sector 1,TRS,938.262500,FM,15k,OFF,250KHz,OFF,OFF,OFF
11=Site 002 White Oaks  Sector 1,TRS,938.275000,FM,15k,OFF,250KHz,OFF,OFF,OFF
12=Site 002 White Oaks  Sector 1,TRS,938.287500,FM,15k,OFF,250KHz,OFF,OFF,OFF
13=Site 002 White Oaks  Sector 1,TRS,938.300000,FM,15k,OFF,250KHz,OFF,OFF,OFF
14=Site 003 White Oaks  Sector 2,TRS,938.312500,FM,15k,OFF,250KHz,OFF,OFF,OFF
15=Site 003 White Oaks  Sector 2,TRS,938.325000,FM,15k,OFF,250KHz,OFF,OFF,OFF
16=Site 003 White Oaks  Sector 2,TRS,938.337500,FM,15k,OFF,250KHz,OFF,OFF,OFF
17=Site 003 White Oaks  Sector 2,TRS,938.350000,FM,15k,OFF,250KHz,OFF,OFF,OFF
18=Site 003 White Oaks  Sector 2,TRS,938.362500,FM,15k,OFF,250KHz,OFF,OFF,OFF
19=Site 003 White Oaks  Sector 2,TRS,938.375000,FM,15k,OFF,250KHz,OFF,OFF,OFF
20=Site 004 Rattlesnake Point,TRS,938.575000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK274]
BANKNAME=  OakvilleTrafalgar Memorial Hospital
00=Site 001 OTMH,TRS,938.762500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 OTMH,TRS,938.787500,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK275]
BANKNAME=  General Motors Canada
00=Site 073 Oshawa Car Assembly,TRS,939.012500,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 073 Oshawa Car Assembly,TRS,939.025000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 073 Oshawa Car Assembly,TRS,939.037500,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=Site 073 Oshawa Car Assembly,TRS,939.050000,FM,15k,OFF,250KHz,OFF,OFF,OFF
04=Site 073 Oshawa Car Assembly,TRS,939.062500,FM,15k,OFF,250KHz,OFF,OFF,OFF
05=Site 073 Oshawa Car Assembly,TRS,939.075000,FM,15k,OFF,250KHz,OFF,OFF,OFF
06=Site 073 Oshawa Car Assembly,TRS,939.087500,FM,15k,OFF,250KHz,OFF,OFF,OFF
07=Site 073 Oshawa Car Assembly,TRS,939.100000,FM,15k,OFF,250KHz,OFF,OFF,OFF
08=Site 073 Oshawa Car Assembly,TRS,939.112500,FM,15k,OFF,250KHz,OFF,OFF,OFF
09=Site 073 Oshawa Car Assembly,TRS,939.125000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK276]
BANKNAME=  Mobile Business  Hamilton 900 MHz
00=Site 002 Unconfirmed LCN,TRS,939.600000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=Site 001 Confirmed LCN,TRS,939.612500,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=Site 002 Unconfirmed LCN,TRS,939.625000,FM,15k,OFF,250KHz,OFF,OFF,OFF

[BANK277]
BANKNAME=23 cm Band
00=VE3YYZAD   DSTAR,Ham,1250.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF
01=VA3GTU  Toronto,Ham,1284.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF
02=VE3VGA  Toronto,Ham,1285.000000,FM,15k,OFF,250KHz,OFF,OFF,OFF
03=VE3YYZA   DSTAR,Ham,1287.500000,FM,15k,OFF,250KHz,OFF,OFF,OFF

